In [7]:
import pandas as pd
loans  = pd.read_csv('data/evaluation/loans.csv')
pay = pd.read_csv('data/evaluation/payments.csv')
merged_df = pd.merge(loans, pay, on='loanId', how='inner')

In [8]:
merged_df

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,...,clarityFraudId,hasCF,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.0,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,...,58ab2121e4b0bf80497352a1,1,1,False,2017-03-03T05:00:00,66.33,130.14,196.47,Checked,NaN
1,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.0,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,...,58ab2121e4b0bf80497352a1,1,2,False,2017-03-17T04:00:00,26.36,170.11,196.47,Pending,NaN
2,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.0,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,...,58ab2121e4b0bf80497352a1,1,3,False,2017-03-31T04:00:00,31.17,165.30,196.47,NaN,NaN
3,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.0,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,...,58ab2121e4b0bf80497352a1,1,4,False,2017-04-14T04:00:00,36.84,159.63,196.47,NaN,NaN
4,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.0,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,...,58ab2121e4b0bf80497352a1,1,5,False,2017-04-28T04:00:00,43.56,152.91,196.47,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.0,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,...,57cf287be4b09249a15fa807,1,9,False,2017-04-21T04:00:00,65.63,116.31,181.94,NaN,NaN
16641,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.0,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,...,57cf287be4b09249a15fa807,1,10,False,2017-05-05T04:00:00,80.48,101.46,181.94,NaN,NaN
16642,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.0,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,...,57cf287be4b09249a15fa807,1,11,False,2017-05-19T04:00:00,98.69,83.25,181.94,NaN,NaN
16643,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.0,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,...,57cf287be4b09249a15fa807,1,12,False,2017-06-02T04:00:00,121.03,60.91,181.94,NaN,NaN
16644,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.0,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,...,57cf287be4b09249a15fa807,1,13,False,2017-06-16T04:00:00,148.14,33.52,181.66,NaN,NaN

In [82]:
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c[

458738

(576682, 19)

In [41]:
duplicated_ids = loans[loans.duplicated(subset='id', keep=False)]

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-07399092,beff4989be82aab4a5b47679216942fd,B,360.0,2016-02-23T17:29:01.940000,False,NaN,0.0,False,0,Withdrawn Application,500.0,978.27,IL,bvMandatory,6,NaN,5669ef78e4b0c9d3936440e6,1
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.0,2016-01-19T22:07:36.778000,True,2016-01-20T15:49:18.846000,0.0,True,1,Paid Off Loan,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
2,LL-I-10707532,3c174ae9e2505a5f9ddbff9843281845,B,590.0,2016-08-01T13:51:14.709000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1199.45,MO,bvMandatory,3,NaN,579eab11e4b0d0502870ef2f,1
3,LL-I-02272596,9be6f443bb97db7e95fa0c281d34da91,B,360.0,2015-08-06T23:58:08.880000,False,NaN,0.0,False,0,Withdrawn Application,500.0,1074.05,IL,bvMandatory,3,NaN,555b1e95e4b0f6f11b267c18,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.0,2016-06-05T22:31:34.304000,False,NaN,0.0,False,0,Rejected,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576677,LL-I-12122269,801262d04720d32040612759857f4147,B,590.0,2016-11-08T17:32:33.554000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1292.41,NV,bvMandatory,3,NaN,58220cdde4b051c58d919c1f,1
576678,LL-I-16183462,e37750de9d99a67e0fa96a51e86fdf5b,S,490.0,2017-01-24T22:20:59.818000,False,NaN,0.0,False,0,Withdrawn Application,1000.0,2592.39,MO,lead,25,NaN,5887d349e4b08f249ac45e2f,1
576679,LL-I-06962710,d7e55e85266208ac4c353f42ebcde5ca,B,590.0,2016-02-02T03:05:47.797000,False,NaN,0.0,False,0,Withdrawn Application,300.0,844.75,IN,bvMandatory,6,NaN,550b1f59e4b0d4592e28c84e,1
576680,LL-I-01253468,c3b35307cb36116bf59574f9138d3dad,B,550.0,2015-05-21T20:19:49.639000,False,NaN,0.0,False,0,Withdrawn Application,300.0,770.80,OH,organic,6,NaN,NaN,0
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,I,590.0,2015-11-17T22:04:20.862000,False,NaN,0.0,False,0,Rejected,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

0         beff4989be82aab4a5b47679216942fd
1         464f5d9ae4fa09ece4048d949191865c
2         3c174ae9e2505a5f9ddbff9843281845
3         9be6f443bb97db7e95fa0c281d34da91
4         63b5494f60b5c19c827c7b068443752c
                        ...
576677    801262d04720d32040612759857f4147
576678    e37750de9d99a67e0fa96a51e86fdf5b
576679    d7e55e85266208ac4c353f42ebcde5ca
576680    c3b35307cb36116bf59574f9138d3dad
576681    dc0a43b16c037ee5d0142daebb5db83a
Name: anon_ssn, Length: 576682, dtype: object

(576682, 19)

458738

In [84]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-07399092,beff4989be82aab4a5b47679216942fd,B,360.0,2016-02-23T17:29:01.940000,False,NaN,0.0,False,0,Withdrawn Application,500.0,978.27,IL,bvMandatory,6,NaN,5669ef78e4b0c9d3936440e6,1
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.0,2016-01-19T22:07:36.778000,True,2016-01-20T15:49:18.846000,0.0,True,1,Paid Off Loan,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
2,LL-I-10707532,3c174ae9e2505a5f9ddbff9843281845,B,590.0,2016-08-01T13:51:14.709000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1199.45,MO,bvMandatory,3,NaN,579eab11e4b0d0502870ef2f,1
3,LL-I-02272596,9be6f443bb97db7e95fa0c281d34da91,B,360.0,2015-08-06T23:58:08.880000,False,NaN,0.0,False,0,Withdrawn Application,500.0,1074.05,IL,bvMandatory,3,NaN,555b1e95e4b0f6f11b267c18,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.0,2016-06-05T22:31:34.304000,False,NaN,0.0,False,0,Rejected,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576677,LL-I-12122269,801262d04720d32040612759857f4147,B,590.0,2016-11-08T17:32:33.554000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1292.41,NV,bvMandatory,3,NaN,58220cdde4b051c58d919c1f,1
576678,LL-I-16183462,e37750de9d99a67e0fa96a51e86fdf5b,S,490.0,2017-01-24T22:20:59.818000,False,NaN,0.0,False,0,Withdrawn Application,1000.0,2592.39,MO,lead,25,NaN,5887d349e4b08f249ac45e2f,1
576679,LL-I-06962710,d7e55e85266208ac4c353f42ebcde5ca,B,590.0,2016-02-02T03:05:47.797000,False,NaN,0.0,False,0,Withdrawn Application,300.0,844.75,IN,bvMandatory,6,NaN,550b1f59e4b0d4592e28c84e,1
576680,LL-I-01253468,c3b35307cb36116bf59574f9138d3dad,B,550.0,2015-05-21T20:19:49.639000,False,NaN,0.0,False,0,Withdrawn Application,300.0,770.80,OH,organic,6,NaN,NaN,0
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,I,590.0,2015-11-17T22:04:20.862000,False,NaN,0.0,False,0,Rejected,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [85]:
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\3669421601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
C:\Users\asus\AppData\Local\Temp\ipykernel_49864\3669421601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)

In [75]:
loans_c['loanStatus'].value_counts()

loanStatus
Withdrawn Application          450984
1                               92537
0                               11635
External Collection             11334
New Loan                         8112
Returned Item                    1182
Settled Bankruptcy                326
Pending Paid Off                  169
Pending Rescind                     4
Pending Application                 4
Voided New Loan                     2
Customver Voided New Loan           1
Settlement Pending Paid Off         1
Name: count, dtype: int64

TypeError: Series.corr() got an unexpected keyword argument 'numeric_only'

TypeError: Series.corr() missing 1 required positional argument: 'other'

In [76]:
loans

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-07399092,beff4989be82aab4a5b47679216942fd,B,360.0,2016-02-23T17:29:01.940000,False,NaN,0.0,False,0,Withdrawn Application,500.0,978.27,IL,bvMandatory,6,NaN,5669ef78e4b0c9d3936440e6,1
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.0,2016-01-19T22:07:36.778000,True,2016-01-20T15:49:18.846000,0.0,True,1,Paid Off Loan,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
2,LL-I-10707532,3c174ae9e2505a5f9ddbff9843281845,B,590.0,2016-08-01T13:51:14.709000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1199.45,MO,bvMandatory,3,NaN,579eab11e4b0d0502870ef2f,1
3,LL-I-02272596,9be6f443bb97db7e95fa0c281d34da91,B,360.0,2015-08-06T23:58:08.880000,False,NaN,0.0,False,0,Withdrawn Application,500.0,1074.05,IL,bvMandatory,3,NaN,555b1e95e4b0f6f11b267c18,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.0,2016-06-05T22:31:34.304000,False,NaN,0.0,False,0,Rejected,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576677,LL-I-12122269,801262d04720d32040612759857f4147,B,590.0,2016-11-08T17:32:33.554000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1292.41,NV,bvMandatory,3,NaN,58220cdde4b051c58d919c1f,1
576678,LL-I-16183462,e37750de9d99a67e0fa96a51e86fdf5b,S,490.0,2017-01-24T22:20:59.818000,False,NaN,0.0,False,0,Withdrawn Application,1000.0,2592.39,MO,lead,25,NaN,5887d349e4b08f249ac45e2f,1
576679,LL-I-06962710,d7e55e85266208ac4c353f42ebcde5ca,B,590.0,2016-02-02T03:05:47.797000,False,NaN,0.0,False,0,Withdrawn Application,300.0,844.75,IN,bvMandatory,6,NaN,550b1f59e4b0d4592e28c84e,1
576680,LL-I-01253468,c3b35307cb36116bf59574f9138d3dad,B,550.0,2015-05-21T20:19:49.639000,False,NaN,0.0,False,0,Withdrawn Application,300.0,770.80,OH,organic,6,NaN,NaN,0
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,I,590.0,2015-11-17T22:04:20.862000,False,NaN,0.0,False,0,Rejected,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [91]:
filt = (loans_c['loanStatus'] == 1) | (loans_c['loanStatus'] == 0)

In [95]:
loans_c= loans_c[filt]

In [81]:
loans_c['loanStatus'].value_counts()

loanStatus
1    92537
Name: count, dtype: int64

In [87]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-07399092,beff4989be82aab4a5b47679216942fd,B,360.0,2016-02-23T17:29:01.940000,False,NaN,0.0,False,0,Withdrawn Application,500.0,978.27,IL,bvMandatory,6,NaN,5669ef78e4b0c9d3936440e6,1
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.0,2016-01-19T22:07:36.778000,True,2016-01-20T15:49:18.846000,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
2,LL-I-10707532,3c174ae9e2505a5f9ddbff9843281845,B,590.0,2016-08-01T13:51:14.709000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1199.45,MO,bvMandatory,3,NaN,579eab11e4b0d0502870ef2f,1
3,LL-I-02272596,9be6f443bb97db7e95fa0c281d34da91,B,360.0,2015-08-06T23:58:08.880000,False,NaN,0.0,False,0,Withdrawn Application,500.0,1074.05,IL,bvMandatory,3,NaN,555b1e95e4b0f6f11b267c18,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.0,2016-06-05T22:31:34.304000,False,NaN,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576677,LL-I-12122269,801262d04720d32040612759857f4147,B,590.0,2016-11-08T17:32:33.554000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1292.41,NV,bvMandatory,3,NaN,58220cdde4b051c58d919c1f,1
576678,LL-I-16183462,e37750de9d99a67e0fa96a51e86fdf5b,S,490.0,2017-01-24T22:20:59.818000,False,NaN,0.0,False,0,Withdrawn Application,1000.0,2592.39,MO,lead,25,NaN,5887d349e4b08f249ac45e2f,1
576679,LL-I-06962710,d7e55e85266208ac4c353f42ebcde5ca,B,590.0,2016-02-02T03:05:47.797000,False,NaN,0.0,False,0,Withdrawn Application,300.0,844.75,IN,bvMandatory,6,NaN,550b1f59e4b0d4592e28c84e,1
576680,LL-I-01253468,c3b35307cb36116bf59574f9138d3dad,B,550.0,2015-05-21T20:19:49.639000,False,NaN,0.0,False,0,Withdrawn Application,300.0,770.80,OH,organic,6,NaN,NaN,0
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,I,590.0,2015-11-17T22:04:20.862000,False,NaN,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

        originated  approved  isFunded  hasCF
0            False     False         0      1
1             True      True         1      1
2            False     False         0      1
3            False     False         0      1
4            False     False         0      1
...            ...       ...       ...    ...
576677       False     False         0      1
576678       False     False         0      1
576679       False     False         0      1
576680       False     False         0      0
576681       False     False         0      1

[576426 rows x 4 columns]

In [97]:
loans_d = loans_c

In [101]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.0,2016-01-19 22:07:36.778,True,2016-01-20T15:49:18.846000,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.0,2016-06-05 22:31:34.304,False,NaN,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
12,LL-I-06936557,2f90cd4d32d373e4c044a67fc4b9cb88,I,590.0,2016-02-01 01:56:09.600,False,NaN,0.0,False,0,1,300.0,856.50,TN,bvMandatory,3,NaN,56aebd69e4b0138a4b2d8086,1
14,LL-I-13956713,8f3bd2f82d48d6e3b221247be473d2e9,W,645.0,2016-12-27 12:09:22.807,False,NaN,0.0,False,0,1,600.0,2056.98,RI,bvMandatory,3,NaN,58625b73e4b08f246a81bad8,1
24,LL-I-09038126,2b8352dbdef42c27292d45163d69c608,W,590.0,2016-05-02 15:40:00.482,False,NaN,0.0,False,0,1,500.0,1613.20,OH,bvMandatory,6,NaN,572cc478e4b0c402fbcd9779,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576663,LL-I-13591246,380420fc3cad8faebb441bac210879f9,W,645.0,2016-12-20 17:58:33.850,False,NaN,0.0,False,0,1,800.0,2742.45,KY,bvMandatory,3,NaN,5859725ce4b08f24646d46ec,1
576666,LL-I-11809630,ad6970cdb83f6f5fc0154ac8e2d6746a,W,590.0,2016-09-06 18:19:07.545,False,NaN,0.0,False,0,1,300.0,954.49,NV,bvMandatory,3,NaN,57cf0c12e4b09249a10cf0bc,1
576669,LL-I-05663063,0c570fc2f50dac99c26c514afe3b1ce4,I,601.0,2015-12-13 15:35:01.477,False,NaN,0.0,False,0,1,600.0,1853.74,NC,bvMandatory,6,NaN,566d911be4b098050bba49ea,1
576674,LL-I-14793786,9cbc945e8042712d874675654fec23dd,B,490.0,2017-01-11 06:06:25.821,False,NaN,0.0,False,0,1,500.0,1274.65,MO,bvMandatory,6,NaN,5875cc98e4b08f247c4f7138,1
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,I,590.0,2015-11-17 22:04:20.862,False,NaN,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [104]:
loans_c['originatedDate'] = pd.to_datetime(loans_c['originatedDate'], errors='coerce')

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\3392089910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loans_c['originatedDate'] = pd.to_datetime(loans_c['originatedDate'], errors='coerce')

nPaidOff
0.0     99747
1.0      2743
2.0       881
3.0       363
4.0       176
5.0        93
6.0        57
7.0        30
8.0        20
9.0         9
13.0        9
11.0        8
10.0        5
19.0        5
18.0        5
14.0        4
20.0        3
12.0        2
15.0        1
21.0        1
17.0        1
16.0        1
Name: count, dtype: int64

In [110]:
loans_d = loans_c

In [113]:
loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\1351026229.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)
C:\Users\asus\AppData\Local\Temp\ipykernel_49864\1351026229.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)
C:\Users\asus\AppData\Local\Temp\ipykernel_49864\1351026229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)

In [114]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,0.071429,199.0,2016-01-19 22:07:36.778,True,2016-01-20 15:49:18.846,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,0.071429,590.0,2016-06-05 22:31:34.304,False,NaT,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
12,LL-I-06936557,2f90cd4d32d373e4c044a67fc4b9cb88,0.000000,590.0,2016-02-01 01:56:09.600,False,NaT,0.0,False,0,1,300.0,856.50,TN,bvMandatory,3,NaN,56aebd69e4b0138a4b2d8086,1
14,LL-I-13956713,8f3bd2f82d48d6e3b221247be473d2e9,0.142857,645.0,2016-12-27 12:09:22.807,False,NaT,0.0,False,0,1,600.0,2056.98,RI,bvMandatory,3,NaN,58625b73e4b08f246a81bad8,1
24,LL-I-09038126,2b8352dbdef42c27292d45163d69c608,0.142857,590.0,2016-05-02 15:40:00.482,False,NaT,0.0,False,0,1,500.0,1613.20,OH,bvMandatory,6,NaN,572cc478e4b0c402fbcd9779,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576663,LL-I-13591246,380420fc3cad8faebb441bac210879f9,0.142857,645.0,2016-12-20 17:58:33.850,False,NaT,0.0,False,0,1,800.0,2742.45,KY,bvMandatory,3,NaN,5859725ce4b08f24646d46ec,1
576666,LL-I-11809630,ad6970cdb83f6f5fc0154ac8e2d6746a,0.142857,590.0,2016-09-06 18:19:07.545,False,NaT,0.0,False,0,1,300.0,954.49,NV,bvMandatory,3,NaN,57cf0c12e4b09249a10cf0bc,1
576669,LL-I-05663063,0c570fc2f50dac99c26c514afe3b1ce4,0.000000,601.0,2015-12-13 15:35:01.477,False,NaT,0.0,False,0,1,600.0,1853.74,NC,bvMandatory,6,NaN,566d911be4b098050bba49ea,1
576674,LL-I-14793786,9cbc945e8042712d874675654fec23dd,0.071429,490.0,2017-01-11 06:06:25.821,False,NaT,0.0,False,0,1,500.0,1274.65,MO,bvMandatory,6,NaN,5875cc98e4b08f247c4f7138,1
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,0.000000,590.0,2015-11-17 22:04:20.862,False,NaT,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [115]:
loans_c.isin(['lionpay']).any()

loanId                              False
anon_ssn                            False
payFrequency                        False
apr                                 False
applicationDate                     False
originated                          False
originatedDate                      False
nPaidOff                            False
approved                            False
isFunded                            False
loanStatus                          False
loanAmount                          False
originallyScheduledPaymentAmount    False
state                               False
leadType                             True
leadCost                            False
fpStatus                            False
clarityFraudId                      False
hasCF                               False
dtype: bool

In [116]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-00000021,1,False,2014-12-19T05:00:00,22.33,147.28,169.61,Checked,NaN
1,LL-I-00000021,2,False,2015-01-02T05:00:00,26.44,143.17,169.61,Checked,NaN
2,LL-I-00000021,3,False,2015-01-16T05:00:00,31.30,138.31,169.61,Checked,NaN
3,LL-I-00000021,4,False,2015-01-30T05:00:00,37.07,132.54,169.61,Checked,NaN
4,LL-I-00000021,5,False,2015-02-13T05:00:00,43.89,125.72,169.61,Checked,NaN
...,...,...,...,...,...,...,...,...,...
672714,LL-I-18629478,8,False,2017-07-14T04:00:00,45.62,17.67,63.29,NaN,NaN
672715,LL-I-18629478,9,False,2017-07-31T04:00:00,45.67,17.62,63.29,NaN,NaN
672716,LL-I-18629478,10,False,2017-08-15T04:00:00,51.12,12.17,63.29,NaN,NaN
672717,LL-I-18629478,11,False,2017-08-31T04:00:00,54.35,8.94,63.29,NaN,NaN
672718,LL-I-18629478,12,False,2017-09-15T04:00:00,58.83,4.36,63.19,NaN,NaN

In [119]:
pay['loanId'].value_counts()

loanId
LL-I-17454600    105
LL-I-09757835    105
LL-I-08320897    105
LL-I-12230332    105
LL-I-18166243    104
                ...
LL-I-09404534      6
LL-I-17429188      6
LL-I-14152033      6
LL-I-13141621      6
LL-I-01138268      3
Name: count, Length: 38952, dtype: int64

In [120]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,0.071429,199.0,2016-01-19 22:07:36.778,True,2016-01-20 15:49:18.846,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,0.071429,590.0,2016-06-05 22:31:34.304,False,NaT,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
12,LL-I-06936557,2f90cd4d32d373e4c044a67fc4b9cb88,0.000000,590.0,2016-02-01 01:56:09.600,False,NaT,0.0,False,0,1,300.0,856.50,TN,bvMandatory,3,NaN,56aebd69e4b0138a4b2d8086,1
14,LL-I-13956713,8f3bd2f82d48d6e3b221247be473d2e9,0.142857,645.0,2016-12-27 12:09:22.807,False,NaT,0.0,False,0,1,600.0,2056.98,RI,bvMandatory,3,NaN,58625b73e4b08f246a81bad8,1
24,LL-I-09038126,2b8352dbdef42c27292d45163d69c608,0.142857,590.0,2016-05-02 15:40:00.482,False,NaT,0.0,False,0,1,500.0,1613.20,OH,bvMandatory,6,NaN,572cc478e4b0c402fbcd9779,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576663,LL-I-13591246,380420fc3cad8faebb441bac210879f9,0.142857,645.0,2016-12-20 17:58:33.850,False,NaT,0.0,False,0,1,800.0,2742.45,KY,bvMandatory,3,NaN,5859725ce4b08f24646d46ec,1
576666,LL-I-11809630,ad6970cdb83f6f5fc0154ac8e2d6746a,0.142857,590.0,2016-09-06 18:19:07.545,False,NaT,0.0,False,0,1,300.0,954.49,NV,bvMandatory,3,NaN,57cf0c12e4b09249a10cf0bc,1
576669,LL-I-05663063,0c570fc2f50dac99c26c514afe3b1ce4,0.000000,601.0,2015-12-13 15:35:01.477,False,NaT,0.0,False,0,1,600.0,1853.74,NC,bvMandatory,6,NaN,566d911be4b098050bba49ea,1
576674,LL-I-14793786,9cbc945e8042712d874675654fec23dd,0.071429,490.0,2017-01-11 06:06:25.821,False,NaT,0.0,False,0,1,500.0,1274.65,MO,bvMandatory,6,NaN,5875cc98e4b08f247c4f7138,1
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,0.000000,590.0,2015-11-17 22:04:20.862,False,NaT,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [122]:
loans_c['applicationDate'].nunique()

104071

In [123]:
loans_c.shape

(104172, 19)

In [140]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-00000021,1,False,2014-12-19T05:00:00,22.33,147.28,169.61,Checked,NaN
1,LL-I-00000021,2,False,2015-01-02T05:00:00,26.44,143.17,169.61,Checked,NaN
2,LL-I-00000021,3,False,2015-01-16T05:00:00,31.30,138.31,169.61,Checked,NaN
3,LL-I-00000021,4,False,2015-01-30T05:00:00,37.07,132.54,169.61,Checked,NaN
4,LL-I-00000021,5,False,2015-02-13T05:00:00,43.89,125.72,169.61,Checked,NaN
...,...,...,...,...,...,...,...,...,...
672714,LL-I-18629478,8,False,2017-07-14T04:00:00,45.62,17.67,63.29,NaN,NaN
672715,LL-I-18629478,9,False,2017-07-31T04:00:00,45.67,17.62,63.29,NaN,NaN
672716,LL-I-18629478,10,False,2017-08-15T04:00:00,51.12,12.17,63.29,NaN,NaN
672717,LL-I-18629478,11,False,2017-08-31T04:00:00,54.35,8.94,63.29,NaN,NaN
672718,LL-I-18629478,12,False,2017-09-15T04:00:00,58.83,4.36,63.19,NaN,NaN

In [147]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,0.071429,199.0,2016-01-19 22:07:36.778,True,2016-01-20 15:49:18.846,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,0.071429,590.0,2016-06-05 22:31:34.304,False,NaT,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
12,LL-I-06936557,2f90cd4d32d373e4c044a67fc4b9cb88,0.000000,590.0,2016-02-01 01:56:09.600,False,NaT,0.0,False,0,1,300.0,856.50,TN,bvMandatory,3,NaN,56aebd69e4b0138a4b2d8086,1
14,LL-I-13956713,8f3bd2f82d48d6e3b221247be473d2e9,0.142857,645.0,2016-12-27 12:09:22.807,False,NaT,0.0,False,0,1,600.0,2056.98,RI,bvMandatory,3,NaN,58625b73e4b08f246a81bad8,1
24,LL-I-09038126,2b8352dbdef42c27292d45163d69c608,0.142857,590.0,2016-05-02 15:40:00.482,False,NaT,0.0,False,0,1,500.0,1613.20,OH,bvMandatory,6,NaN,572cc478e4b0c402fbcd9779,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576663,LL-I-13591246,380420fc3cad8faebb441bac210879f9,0.142857,645.0,2016-12-20 17:58:33.850,False,NaT,0.0,False,0,1,800.0,2742.45,KY,bvMandatory,3,NaN,5859725ce4b08f24646d46ec,1
576666,LL-I-11809630,ad6970cdb83f6f5fc0154ac8e2d6746a,0.142857,590.0,2016-09-06 18:19:07.545,False,NaT,0.0,False,0,1,300.0,954.49,NV,bvMandatory,3,NaN,57cf0c12e4b09249a10cf0bc,1
576669,LL-I-05663063,0c570fc2f50dac99c26c514afe3b1ce4,0.000000,601.0,2015-12-13 15:35:01.477,False,NaT,0.0,False,0,1,600.0,1853.74,NC,bvMandatory,6,NaN,566d911be4b098050bba49ea,1
576674,LL-I-14793786,9cbc945e8042712d874675654fec23dd,0.071429,490.0,2017-01-11 06:06:25.821,False,NaT,0.0,False,0,1,500.0,1274.65,MO,bvMandatory,6,NaN,5875cc98e4b08f247c4f7138,1
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,0.000000,590.0,2015-11-17 22:04:20.862,False,NaT,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [148]:
loans_c['originated'].value_counts()

originated
False    86268
True     17904
Name: count, dtype: int64

In [150]:
loans_c['originatedDate'].isna().value_counts()

originatedDate
True     86282
False    17890
Name: count, dtype: int64

In [151]:
loans_c

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,0.071429,199.0,2016-01-19 22:07:36.778,True,2016-01-20 15:49:18.846,0.0,True,1,0,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,0.071429,590.0,2016-06-05 22:31:34.304,False,NaT,0.0,False,0,1,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
12,LL-I-06936557,2f90cd4d32d373e4c044a67fc4b9cb88,0.000000,590.0,2016-02-01 01:56:09.600,False,NaT,0.0,False,0,1,300.0,856.50,TN,bvMandatory,3,NaN,56aebd69e4b0138a4b2d8086,1
14,LL-I-13956713,8f3bd2f82d48d6e3b221247be473d2e9,0.142857,645.0,2016-12-27 12:09:22.807,False,NaT,0.0,False,0,1,600.0,2056.98,RI,bvMandatory,3,NaN,58625b73e4b08f246a81bad8,1
24,LL-I-09038126,2b8352dbdef42c27292d45163d69c608,0.142857,590.0,2016-05-02 15:40:00.482,False,NaT,0.0,False,0,1,500.0,1613.20,OH,bvMandatory,6,NaN,572cc478e4b0c402fbcd9779,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576663,LL-I-13591246,380420fc3cad8faebb441bac210879f9,0.142857,645.0,2016-12-20 17:58:33.850,False,NaT,0.0,False,0,1,800.0,2742.45,KY,bvMandatory,3,NaN,5859725ce4b08f24646d46ec,1
576666,LL-I-11809630,ad6970cdb83f6f5fc0154ac8e2d6746a,0.142857,590.0,2016-09-06 18:19:07.545,False,NaT,0.0,False,0,1,300.0,954.49,NV,bvMandatory,3,NaN,57cf0c12e4b09249a10cf0bc,1
576669,LL-I-05663063,0c570fc2f50dac99c26c514afe3b1ce4,0.000000,601.0,2015-12-13 15:35:01.477,False,NaT,0.0,False,0,1,600.0,1853.74,NC,bvMandatory,6,NaN,566d911be4b098050bba49ea,1
576674,LL-I-14793786,9cbc945e8042712d874675654fec23dd,0.071429,490.0,2017-01-11 06:06:25.821,False,NaT,0.0,False,0,1,500.0,1274.65,MO,bvMandatory,6,NaN,5875cc98e4b08f247c4f7138,1
576681,LL-I-04733921,dc0a43b16c037ee5d0142daebb5db83a,0.000000,590.0,2015-11-17 22:04:20.862,False,NaT,0.0,False,0,1,400.0,1214.63,OH,bvMandatory,6,NaN,564f801ae4b05a02bef951e8,1

In [153]:
loans_c['loanStatus'].value_counts()

loanStatus
1    92537
0    11635
Name: count, dtype: int64

In [156]:
rmd_d = pd.read_csv('ramadan/data/Testing/test_Demographics.csv')

In [177]:
rmd_l = pd.read_csv('ramadan/data/Testing/test_Laboratory_Findings.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Medical_History.csv')
rmd_v=pd.read_csv('ramadan/data/Testing/test_Vital_Signs.csv')

In [158]:
rmd_l

,id,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_max,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS2_bilirubin_max,OBS2_bilirubin_min,OBS1_bun_max,...,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min
0,214826,2.3,2.3,NaN,NaN,0.4,0.4,NaN,NaN,31.0,...,NaN,NaN,27.4,27.4,NaN,NaN,136.0,134.0,NaN,NaN
1,190593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,216.0,216.0,32.9,32.9,NaN,NaN,139.0,139.0,NaN,NaN
2,244158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,131.0,34.9,29.3,NaN,NaN,NaN,NaN,NaN,NaN
3,238278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,195.0,195.0,39.9,39.9,NaN,NaN,142.0,142.0,NaN,NaN
4,198305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,44.0,44.0,NaN,NaN,134.0,134.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26027,258430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,...,NaN,NaN,33.0,30.0,NaN,NaN,140.0,140.0,NaN,NaN
26028,239532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26029,198342,4.3,4.0,NaN,NaN,0.7,0.6,NaN,NaN,11.0,...,NaN,NaN,44.0,44.0,NaN,NaN,138.0,137.0,NaN,NaN
26030,255318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,36.0,33.0,NaN,NaN,141.0,139.0,NaN,NaN
26031,222562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,...,NaN,NaN,33.0,23.0,33.0,33.0,141.0,141.0,NaN,NaN

In [159]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,214826,68.0,Caucasian,M,73.90,180.3,22.732803
1,190593,68.0,Caucasian,M,82.20,172.7,27.560503
2,244158,45.0,Caucasian,M,116.60,190.5,32.129842
3,238278,71.0,Caucasian,M,121.70,177.8,38.497016
4,198305,65.0,African American,M,78.40,172.7,26.286417
...,...,...,...,...,...,...,...
26027,258430,77.0,Caucasian,F,NaN,NaN,NaN
26028,239532,82.0,Caucasian,F,NaN,NaN,NaN
26029,198342,24.0,African American,M,153.40,190.5,42.270307
26030,255318,51.0,Other/Unknown,F,63.05,170.2,21.765366
26031,222562,81.0,Caucasian,M,83.90,185.4,24.408579

In [172]:
rmd_d['gender_identity'] = rmd_d['gender_identity'].replace(['M','F'],[1,0])

In [171]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,214826,68.0,Caucasian,1.0,73.90,180.3,22.732803
1,190593,68.0,Caucasian,1.0,82.20,172.7,27.560503
2,244158,45.0,Caucasian,1.0,116.60,190.5,32.129842
3,238278,71.0,Caucasian,1.0,121.70,177.8,38.497016
4,198305,65.0,African American,1.0,78.40,172.7,26.286417
...,...,...,...,...,...,...,...
26027,258430,77.0,Caucasian,0.0,NaN,NaN,NaN
26028,239532,82.0,Caucasian,0.0,NaN,NaN,NaN
26029,198342,24.0,African American,1.0,153.40,190.5,42.270307
26030,255318,51.0,Other/Unknown,0.0,63.05,170.2,21.765366
26031,222562,81.0,Caucasian,1.0,83.90,185.4,24.408579

In [181]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,214826,68.0,Caucasian,1.0,73.90,180.3,22.732803
1,190593,68.0,Caucasian,1.0,82.20,172.7,27.560503
2,244158,45.0,Caucasian,1.0,116.60,190.5,32.129842
3,238278,71.0,Caucasian,1.0,121.70,177.8,38.497016
4,198305,65.0,African American,1.0,78.40,172.7,26.286417
...,...,...,...,...,...,...,...
26025,246917,60.0,African American,0.0,120.60,165.1,44.243875
26026,248330,41.0,Caucasian,0.0,91.00,162.6,34.419163
26029,198342,24.0,African American,1.0,153.40,190.5,42.270307
26030,255318,51.0,Other/Unknown,0.0,63.05,170.2,21.765366
26031,222562,81.0,Caucasian,1.0,83.90,185.4,24.408579

In [176]:
rmd_d['ethnic_group'].value_counts()

ethnic_group
Caucasian           20054
African American     2801
Other/Unknown        1225
Hispanic              970
Asian                 450
Native American       206
Name: count, dtype: int64

In [183]:
rmd_d = pd.get_dummies(rmd_d,columns=['ethnic_group'])

In [184]:
rmd_d

,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown
0,214826,68.0,1.0,73.90,180.3,22.732803,False,False,True,False,False,False
1,190593,68.0,1.0,82.20,172.7,27.560503,False,False,True,False,False,False
2,244158,45.0,1.0,116.60,190.5,32.129842,False,False,True,False,False,False
3,238278,71.0,1.0,121.70,177.8,38.497016,False,False,True,False,False,False
4,198305,65.0,1.0,78.40,172.7,26.286417,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
26025,246917,60.0,0.0,120.60,165.1,44.243875,True,False,False,False,False,False
26026,248330,41.0,0.0,91.00,162.6,34.419163,False,False,True,False,False,False
26029,198342,24.0,1.0,153.40,190.5,42.270307,True,False,False,False,False,False
26030,255318,51.0,0.0,63.05,170.2,21.765366,False,False,False,False,False,True
26031,222562,81.0,1.0,83.90,185.4,24.408579,False,False,True,False,False,False

In [185]:
# %load 
loans  = pd.read_csv('loans.csv')
pay = pd.read_csv('payments.csv')
import pandas as pd
loans  = pd.read_csv('loans.csv')
pay = pd.read_csv('payments.csv')
import pandas as pd
loans  = pd.read_csv('data/train/loans.csv')
pay = pd.read_csv('data/train/payments.csv')
loans
loans['ID'].nunique()
loans['loanId	'].nunique()
loans['loanId'].nunique()
loans.shape()
loans.shape
loans['loandId'].sum()
loans['loanId'].sum()
loans['loanId'].str.len().sum()
loans['loanId']
duplicated_ids = loans[loans.duplicated(subset='id', keep=False)]
loans['loanId'].value_counts
loans['loanId'].value_counts()
loans['loanId'].value_counts().index_sort()
loans['loanId'].value_counts(ascending = True)
loans['loanId'].value_counts(ascending = False)
loans['loanId'].isnan()
loans['anon_ssn']
loans.shape
loans['id'].isna()
loans['loanId'].isna()
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans.loc[filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c[filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
loans_c['anon_ssn'].nunique
loans_c['anon_ssn'].nunique()
loans_c.shape
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],[0,1]) 
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off']],[0,1]) 
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off']],[[0,1]]) 
 loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0) 
 loans_c= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
loans
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans.loc[~filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
 loans_c
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
loans_c
filt = loans_c['loanStatus'] == 0|1
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == (0|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == ('0'|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == ('0'|'1')
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == (0|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == 0
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == 0&1
loans_c.loc[~filt]
filt = loans_c['loanStatus'] != 0|1
loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filtered_loans_c
loans_c
corr = laons_c.corr()
corr
corr = loans_c.corr()
corr
loans_c.corr()
loans_c['applicationDate'].corr()
corr = loans_c['loans_amount'].corr()
corr
corr = loans_c['loanAmount'].corr()
corr
corr = loans_c['loanAmount'].corr(numeric_only=False)

corr
loans_c['originated'].dtype
loans_c
loans_c['loanStatus'].dtype
loans_c['loanStatus'].corr(loans_c['loanAmount'])
loans_c['originatedDate']
loans_c['originatedDate'].count()
loans_c
loans_c['loanStatus'].value_counts()
loans
filt = loans_c['loanStatus'] == 1|0 
loans_c[filt]
loans_c = loans_c[filt]
loans_c = loans_c[filt]
loans_c
loans_c['loanStatus'].value_counts()
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
loans_c
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
filt = loans_c['loanStatus'] == 1 or loans_c['loanStatus'] == 0  
loans_c
filt = loans_c['loanStatus'] == 1 | loans_c['loanStatus'] == 0  
columns_to_remove = loans_c.columns[~loans_c.isin([0, 1]).all()]
loans_c.drop(columns=columns_to_remove)
columns_to_remove = loans_c.columns[~loans_c.isin([0, 1]).all()]
loans_b = loans_c
loans_c.drop(columns=columns_to_remove)
filt = (loans_c['loanStatus'] == 1) | (loans_c['loanStatus'] == 0)
loans_c[filt]
loans_c[filt].value_counts()
loans_c[filt]['loanStatus'].value_counts()
loans_c= loans_c[filt]
loans_c['applicationDate'].dtype
loans_d = loans_c
pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c['applicationDate'] =  pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c['applicationDate'] =  pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c
pd.to_datetime(df['originatedDate'], errors='coerce')
pd.to_datetime(loans_c['originatedDate'], errors='coerce')
loans_c['originatedDate'] = pd.to_datetime(loans_c['originatedDate'], errors='coerce')
loans_c
loans_c['nPaidOff']
loans_c['nPaidOff'].value_counts()
loans_c
loans_d = laons_c
loans_d = loans_c
loans_c
loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7])
loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)
loans_c
loans_c.isin(['lionpay']).any()
pay
pay['loanId']nunique()
pay['loanId'].nunique()
pay['loanId'].value_counts()
loans_c
loans
loans_c['applicationDate'].nunique()
loans_c.shape
pay
pay['paymentReturnCode']
pay['paymentReturnCode'].value_counts
pay['paymentReturnCode'].value_counts()
import numpy as np
pay[pay['paymentReturnCode'] == np.nan]
import numpy as np
pay['paymentReturnCode'] == np.nan
import numpy as np
pay['paymentReturnCode']
import numpy as np
pay['paymentReturnCode'][1]
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
nan_count
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
none_count
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
nan_count
import numpy as np
 pay['paymentReturnCode'].value_counts
import numpy as np
 pay['paymentReturnCode'].value_counts()
import numpy as np
pay['paymentReturnCode'].value_counts()
import numpy as np
pay['paymentReturnCode'] == 'MISSED'
import numpy as np
pay['paymentReturnCode'][pay['paymentReturnCode'] == 'MISSED']
pay
import numpy as np
pay['paymentReturnCode'].isnan
import numpy as np
pay['paymentReturnCode'].isnan()
import numpy as np
pay['paymentReturnCode'].isna()
import numpy as np
pay['paymentReturnCode'].isna().value_counts
import numpy as np
pay['paymentReturnCode'].isna().value_counts()
import numpy as np
pay['paymentReturnCode'].isna().value_counts()

pay['paymentReturnCode'].value_counts()
loans_c
loans_c['originated'].value_counts()
loans_c['originatedDate'].value_counts()
loans_c['originatedDate'].isna().value_counts()
loans_c
rdn = pd.read_csv('loanStatus').value_counts()
loans_c['loanStatus'].value_counts()
rmd = pd.read_csv('ramadan/data/Testing/test_Demographics.csv')
rmd
rmd_d = pd.read_csv('ramadan/data/Testing/test_Demographics.csv')
rmd_l = pd.read_csv('ramadan/data/Testing/test_Laboratory_Findings.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Medical_History.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Vital_Signs.csv')
rmd_l
rmd_d
rmd_d['ethnic_group'].value_counts()
rmd_d['id'].nunique()
rmd_d.loc['gender_identity'].value_counts()
rmd_d['gender_identity'].value_counts()
rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d.loc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.iloc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.loc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.['gender_identity'].replace(['M','F'],[1,0],inplace=True)
rmd_d['gender_identity'].replace(['M','F'],[1,0],inplace=True)
rmd_d['gender_identity'] = rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d
rmd_d['gender_identity'] = rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d.dropa()
rmd_d.dropan()
rmd_d.dropna()
rmd_d['ethnic_group'].value_counts()
rmd_l = pd.read_csv('ramadan/data/Testing/test_Laboratory_Findings.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Medical_History.csv')
rmd_v=pd.read_csv('ramadan/data/Testing/test_Vital_Signs.csv')
rmd_l
pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d.dropna(inplace = True)
rmd_d
pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d = pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d

In [186]:
rmd_d.corr()

,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown
id,1.000000,-0.006357,-0.002507,0.002456,0.000536,0.002204,0.000440,-0.002105,0.006338,0.001001,-0.005492,-0.010162
age_yrs,-0.006357,1.000000,-0.032363,-0.128797,-0.115612,-0.086613,-0.121454,-0.015751,0.149676,-0.023994,-0.061290,-0.055718
gender_identity,-0.002507,-0.032363,1.000000,0.252156,0.681111,-0.040466,-0.023723,-0.006552,0.016039,-0.004911,-0.007005,0.014765
weight_kg,0.002456,-0.128797,0.252156,1.000000,0.385664,0.876156,0.037174,-0.082172,0.029606,-0.039454,0.012491,-0.031869
height_cm,0.000536,-0.115612,0.681111,0.385664,1.000000,-0.065985,0.020886,-0.085053,0.080835,-0.078937,-0.013670,-0.059610
body_mass_index,0.002204,-0.086613,-0.040466,0.876156,-0.065985,1.000000,0.034519,-0.052333,-0.006619,-0.007680,0.022022,-0.008145
ethnic_group_African American,0.000440,-0.121454,-0.023723,0.037174,0.020886,0.034519,1.000000,-0.046980,-0.659377,-0.069422,-0.032015,-0.080157
ethnic_group_Asian,-0.002105,-0.015751,-0.006552,-0.082172,-0.085053,-0.052333,-0.046980,1.000000,-0.248770,-0.026191,-0.012079,-0.030242
ethnic_group_Caucasian,0.006338,0.149676,0.016039,0.029606,0.080835,-0.006619,-0.659377,-0.248770,1.000000,-0.367601,-0.169525,-0.424449
ethnic_group_Hispanic,0.001001,-0.023994,-0.004911,-0.039454,-0.078937,-0.007680,-0.069422,-0.026191,-0.367601,1.000000,-0.017848,-0.044687
ethnic_group_Native American,-0.005492,-0.061290,-0.007005,0.012491,-0.013670,0.022022,-0.032015,-0.012079,-0.169525,-0.017848,1.000000,-0.020608
ethnic_group_Other/Unknown,-0.010162,-0.055718,0.014765,-0.031869,-0.059610,-0.008145,-0.080157,-0.030242,-0.424449,-0.044687,-0.020608,1.000000

In [187]:
rmd_l

,id,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_max,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS2_bilirubin_max,OBS2_bilirubin_min,OBS1_bun_max,...,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min
0,214826,2.3,2.3,NaN,NaN,0.4,0.4,NaN,NaN,31.0,...,NaN,NaN,27.4,27.4,NaN,NaN,136.0,134.0,NaN,NaN
1,190593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,216.0,216.0,32.9,32.9,NaN,NaN,139.0,139.0,NaN,NaN
2,244158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,131.0,34.9,29.3,NaN,NaN,NaN,NaN,NaN,NaN
3,238278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,195.0,195.0,39.9,39.9,NaN,NaN,142.0,142.0,NaN,NaN
4,198305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,44.0,44.0,NaN,NaN,134.0,134.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26027,258430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,...,NaN,NaN,33.0,30.0,NaN,NaN,140.0,140.0,NaN,NaN
26028,239532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26029,198342,4.3,4.0,NaN,NaN,0.7,0.6,NaN,NaN,11.0,...,NaN,NaN,44.0,44.0,NaN,NaN,138.0,137.0,NaN,NaN
26030,255318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,36.0,33.0,NaN,NaN,141.0,139.0,NaN,NaN
26031,222562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,...,NaN,NaN,33.0,23.0,33.0,33.0,141.0,141.0,NaN,NaN

In [188]:
# %load 
loans  = pd.read_csv('loans.csv')
pay = pd.read_csv('payments.csv')
import pandas as pd
loans  = pd.read_csv('loans.csv')
pay = pd.read_csv('payments.csv')
import pandas as pd
loans  = pd.read_csv('data/train/loans.csv')
pay = pd.read_csv('data/train/payments.csv')
loans
loans['ID'].nunique()
loans['loanId	'].nunique()
loans['loanId'].nunique()
loans.shape()
loans.shape
loans['loandId'].sum()
loans['loanId'].sum()
loans['loanId'].str.len().sum()
loans['loanId']
duplicated_ids = loans[loans.duplicated(subset='id', keep=False)]
loans['loanId'].value_counts
loans['loanId'].value_counts()
loans['loanId'].value_counts().index_sort()
loans['loanId'].value_counts(ascending = True)
loans['loanId'].value_counts(ascending = False)
loans['loanId'].isnan()
loans['anon_ssn']
loans.shape
loans['id'].isna()
loans['loanId'].isna()
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans.loc[filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c[filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
loans_c['anon_ssn'].nunique
loans_c['anon_ssn'].nunique()
loans_c.shape
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],[0,1]) 
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off']],[0,1]) 
 loans_c['loanStatus'].replace([['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off']],[[0,1]]) 
 loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0) 
 loans_c= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
loans
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans.loc[~filt]
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
 loans_c
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
loans_c
filt = loans_c['loanStatus'] == 0|1
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == (0|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == ('0'|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == ('0'|'1')
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == (0|1)
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == 0
loans_c.loc[~filt]
filt = loans_c['loanStatus'] == 0&1
loans_c.loc[~filt]
filt = loans_c['loanStatus'] != 0|1
loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filt = (loans_c['loanStatus'] != 0) & (loans_c['loanStatus'] != 1)
filtered_loans_c = loans_c.loc[filt]
filtered_loans_c
loans_c
corr = laons_c.corr()
corr
corr = loans_c.corr()
corr
loans_c.corr()
loans_c['applicationDate'].corr()
corr = loans_c['loans_amount'].corr()
corr
corr = loans_c['loanAmount'].corr()
corr
corr = loans_c['loanAmount'].corr(numeric_only=False)

corr
loans_c['originated'].dtype
loans_c
loans_c['loanStatus'].dtype
loans_c['loanStatus'].corr(loans_c['loanAmount'])
loans_c['originatedDate']
loans_c['originatedDate'].count()
loans_c
loans_c['loanStatus'].value_counts()
loans
filt = loans_c['loanStatus'] == 1|0 
loans_c[filt]
loans_c = loans_c[filt]
loans_c = loans_c[filt]
loans_c
loans_c['loanStatus'].value_counts()
filt = loans['loanId'].isna() | loans['loanId'].isnull()
loans_c= loans.loc[~filt]
loans_c['anon_ssn'].nunique()
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c.loc['loanStatus']= loans_c.loc['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
loans_c
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Paid Off Loan','Charged Off Paid Off','Settlement Paid Off'],0)
 loans_c['loanStatus']= loans_c['loanStatus'].replace(['Rejected','Internal Collection','CSR Voided New Loan','Customer Voided New Loan','Credit Return Void','Pending Application Fee','Charged Off'],1)
filt = loans_c['loanStatus'] == 1 or loans_c['loanStatus'] == 0  
loans_c
filt = loans_c['loanStatus'] == 1 | loans_c['loanStatus'] == 0  
columns_to_remove = loans_c.columns[~loans_c.isin([0, 1]).all()]
loans_c.drop(columns=columns_to_remove)
columns_to_remove = loans_c.columns[~loans_c.isin([0, 1]).all()]
loans_b = loans_c
loans_c.drop(columns=columns_to_remove)
filt = (loans_c['loanStatus'] == 1) | (loans_c['loanStatus'] == 0)
loans_c[filt]
loans_c[filt].value_counts()
loans_c[filt]['loanStatus'].value_counts()
loans_c= loans_c[filt]
loans_c['applicationDate'].dtype
loans_d = loans_c
pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c['applicationDate'] =  pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c['applicationDate'] =  pd.to_datetime(loans_c['applicationDate'], errors='coerce')
loans_c
pd.to_datetime(df['originatedDate'], errors='coerce')
pd.to_datetime(loans_c['originatedDate'], errors='coerce')
loans_c['originatedDate'] = pd.to_datetime(loans_c['originatedDate'], errors='coerce')
loans_c
loans_c['nPaidOff']
loans_c['nPaidOff'].value_counts()
loans_c
loans_d = laons_c
loans_d = loans_c
loans_c
loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7])
loans_c['payFrequency'].replace(['B','I','M','S','W'],[1/14,0,1/30,1/15,1/7],inplace = True)
loans_c
loans_c.isin(['lionpay']).any()
pay
pay['loanId']nunique()
pay['loanId'].nunique()
pay['loanId'].value_counts()
loans_c
loans
loans_c['applicationDate'].nunique()
loans_c.shape
pay
pay['paymentReturnCode']
pay['paymentReturnCode'].value_counts
pay['paymentReturnCode'].value_counts()
import numpy as np
pay[pay['paymentReturnCode'] == np.nan]
import numpy as np
pay['paymentReturnCode'] == np.nan
import numpy as np
pay['paymentReturnCode']
import numpy as np
pay['paymentReturnCode'][1]
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
nan_count
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
none_count
import numpy as np
nan_count = pay['paymentReturnCode'].isna().sum()
none_count = pay['paymentReturnCode'].apply(lambda x: x is None).sum()
nan_count
import numpy as np
 pay['paymentReturnCode'].value_counts
import numpy as np
 pay['paymentReturnCode'].value_counts()
import numpy as np
pay['paymentReturnCode'].value_counts()
import numpy as np
pay['paymentReturnCode'] == 'MISSED'
import numpy as np
pay['paymentReturnCode'][pay['paymentReturnCode'] == 'MISSED']
pay
import numpy as np
pay['paymentReturnCode'].isnan
import numpy as np
pay['paymentReturnCode'].isnan()
import numpy as np
pay['paymentReturnCode'].isna()
import numpy as np
pay['paymentReturnCode'].isna().value_counts
import numpy as np
pay['paymentReturnCode'].isna().value_counts()
import numpy as np
pay['paymentReturnCode'].isna().value_counts()

pay['paymentReturnCode'].value_counts()
loans_c
loans_c['originated'].value_counts()
loans_c['originatedDate'].value_counts()
loans_c['originatedDate'].isna().value_counts()
loans_c
rdn = pd.read_csv('loanStatus').value_counts()
loans_c['loanStatus'].value_counts()
rmd = pd.read_csv('ramadan/data/Testing/test_Demographics.csv')
rmd
rmd_d = pd.read_csv('ramadan/data/Testing/test_Demographics.csv')
rmd_l = pd.read_csv('ramadan/data/Testing/test_Laboratory_Findings.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Medical_History.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Vital_Signs.csv')
rmd_l
rmd_d
rmd_d['ethnic_group'].value_counts()
rmd_d['id'].nunique()
rmd_d.loc['gender_identity'].value_counts()
rmd_d['gender_identity'].value_counts()
rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d.loc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.iloc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.loc['gender_identity'].replace(['M','F'],[1,0])
rmd_d.['gender_identity'].replace(['M','F'],[1,0],inplace=True)
rmd_d['gender_identity'].replace(['M','F'],[1,0],inplace=True)
rmd_d['gender_identity'] = rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d
rmd_d['gender_identity'] = rmd_d['gender_identity'].replace(['M','F'],[1,0])
rmd_d.dropa()
rmd_d.dropan()
rmd_d.dropna()
rmd_d['ethnic_group'].value_counts()
rmd_l = pd.read_csv('ramadan/data/Testing/test_Laboratory_Findings.csv')
rmd_m=pd.read_csv('ramadan/data/Testing/test_Medical_History.csv')
rmd_v=pd.read_csv('ramadan/data/Testing/test_Vital_Signs.csv')
rmd_l
pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d.dropna(inplace = True)
rmd_d
pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d = pd.get_dummies(rmd_d,columns=['ethnic_group'])
rmd_d
load
rmd_d.corr()
rmd_l

In [189]:
rmd_l

,id,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_max,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS2_bilirubin_max,OBS2_bilirubin_min,OBS1_bun_max,...,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min
0,214826,2.3,2.3,NaN,NaN,0.4,0.4,NaN,NaN,31.0,...,NaN,NaN,27.4,27.4,NaN,NaN,136.0,134.0,NaN,NaN
1,190593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,216.0,216.0,32.9,32.9,NaN,NaN,139.0,139.0,NaN,NaN
2,244158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,131.0,34.9,29.3,NaN,NaN,NaN,NaN,NaN,NaN
3,238278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,195.0,195.0,39.9,39.9,NaN,NaN,142.0,142.0,NaN,NaN
4,198305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,44.0,44.0,NaN,NaN,134.0,134.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26027,258430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,...,NaN,NaN,33.0,30.0,NaN,NaN,140.0,140.0,NaN,NaN
26028,239532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26029,198342,4.3,4.0,NaN,NaN,0.7,0.6,NaN,NaN,11.0,...,NaN,NaN,44.0,44.0,NaN,NaN,138.0,137.0,NaN,NaN
26030,255318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,36.0,33.0,NaN,NaN,141.0,139.0,NaN,NaN
26031,222562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,...,NaN,NaN,33.0,23.0,33.0,33.0,141.0,141.0,NaN,NaN

In [194]:
rmd_l.apply(lambda x:x.count())

id                     26032
OBS1_albumin_max       11774
OBS1_albumin_min       11774
OBS2_albumin_max        2175
OBS2_albumin_min        2175
OBS1_bilirubin_max     10746
OBS1_bilirubin_min     10746
OBS2_bilirubin_max      2017
OBS2_bilirubin_min      2017
OBS1_bun_max           23267
OBS1_bun_min           23267
OBS2_bun_max            4939
OBS2_bun_min            4939
OBS1_creatinine_max    23356
OBS1_creatinine_min    23356
OBS2_creatinine_max     4998
OBS2_creatinine_min     4998
OBS1_glucose_max       24389
OBS1_glucose_min       24389
OBS2_glucose_max       11098
OBS2_glucose_min       11098
OBS1_hematocrit_max    22922
OBS1_hematocrit_min    22922
OBS2_hematocrit_max     5405
OBS2_hematocrit_min     5405
OBS1_sodium_max        23360
OBS1_sodium_min        23360
OBS2_sodium_max         5625
OBS2_sodium_min         5625
dtype: int64

In [212]:
rmd_l

,id,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_max,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS2_bilirubin_max,OBS2_bilirubin_min,OBS1_bun_max,...,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min
0,214826,2.3,2.3,NaN,NaN,0.4,0.4,NaN,NaN,31.0,...,NaN,NaN,27.4,27.4,NaN,NaN,136.0,134.0,NaN,NaN
1,190593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,216.0,216.0,32.9,32.9,NaN,NaN,139.0,139.0,NaN,NaN
2,244158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,131.0,34.9,29.3,NaN,NaN,NaN,NaN,NaN,NaN
3,238278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,195.0,195.0,39.9,39.9,NaN,NaN,142.0,142.0,NaN,NaN
4,198305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,44.0,44.0,NaN,NaN,134.0,134.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26027,258430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,...,NaN,NaN,33.0,30.0,NaN,NaN,140.0,140.0,NaN,NaN
26028,239532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26029,198342,4.3,4.0,NaN,NaN,0.7,0.6,NaN,NaN,11.0,...,NaN,NaN,44.0,44.0,NaN,NaN,138.0,137.0,NaN,NaN
26030,255318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,36.0,33.0,NaN,NaN,141.0,139.0,NaN,NaN
26031,222562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,...,NaN,NaN,33.0,23.0,33.0,33.0,141.0,141.0,NaN,NaN

0        215172.932803
1        190945.460503
2        244544.229842
3        238688.997016
4        198649.386417
             ...
26025    247307.943875
26026    248660.019163
26029    198754.170307
26030    255625.015366
26031    222938.708579
Length: 23886, dtype: object

In [213]:
rmd_m

,id,hiv_aids_status,chronic_liver_disease,liver_function_impaired,immune_compromise,blood_cancer,lymphatic_cancer,advanced_solid_tumor
0,214826,0,0,0,0,0,0,0
1,190593,0,0,0,0,0,0,1
2,244158,0,0,0,0,0,0,0
3,238278,0,1,1,0,0,0,0
4,198305,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
26027,258430,0,0,0,0,0,0,0
26028,239532,0,0,0,0,0,0,0
26029,198342,0,0,0,0,0,0,0
26030,255318,0,0,0,0,1,0,0
26031,222562,0,0,0,0,0,0,0

In [219]:
rmd_v

,id,OBS1_hrate_max,OBS1_hrate_min,OBS2_hrate_max,OBS2_hrate_min,OBS1_reprate_max,OBS1_reprate_min,OBS2_reprate_max,OBS2_reprate_min,OBS1_sysb_max,...,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min
0,214826,119.0,72.0,119.0,108.0,34.0,10.0,26.0,18.0,131.0,...,131.0,115.0,68.0,37.0,68.0,63.0,39.9,37.200,39.5,37.5
1,190593,90.0,57.0,69.0,65.0,39.0,9.0,25.0,9.0,176.0,...,176.0,119.0,80.0,51.0,79.0,57.0,36.7,36.400,36.4,36.4
2,244158,132.0,84.0,126.0,122.0,27.0,14.0,27.0,16.0,176.0,...,156.0,155.0,116.0,75.0,108.0,97.0,37.7,36.700,37.3,37.3
3,238278,96.0,70.0,88.0,82.0,59.0,4.0,30.0,28.0,204.0,...,163.0,136.0,105.0,51.0,78.0,74.0,38.2,36.700,NaN,NaN
4,198305,132.0,96.0,132.0,120.0,44.0,0.0,44.0,10.0,159.0,...,148.0,111.0,106.0,73.0,81.0,73.0,37.2,36.200,36.4,36.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26027,258430,70.0,51.0,62.0,56.0,24.0,11.0,23.0,16.0,172.0,...,134.0,134.0,71.0,48.0,63.0,63.0,37.0,36.600,NaN,NaN
26028,239532,81.0,34.0,81.0,36.0,36.0,0.0,36.0,0.0,90.0,...,75.0,53.0,46.0,25.0,37.0,25.0,NaN,NaN,NaN,NaN
26029,198342,108.0,87.0,101.0,90.0,80.0,6.0,59.0,18.0,151.0,...,136.0,136.0,91.0,51.0,62.0,62.0,37.2,37.100,37.2,37.2
26030,255318,86.0,71.0,85.0,79.0,33.0,16.0,33.0,26.0,134.0,...,133.0,71.0,88.0,49.0,88.0,49.0,35.1,31.889,34.4,33.6
26031,222562,110.0,70.0,85.0,70.0,31.0,8.0,28.0,8.0,151.0,...,128.0,70.0,80.0,44.0,65.0,47.0,37.1,35.500,37.1,36.3

In [220]:
rmd_v.apply(lambda x:x.count())

id                  26032
OBS1_hrate_max      25980
OBS1_hrate_min      25980
OBS2_hrate_max      25180
OBS2_hrate_min      25180
OBS1_reprate_max    25914
OBS1_reprate_min    25914
OBS2_reprate_max    24707
OBS2_reprate_min    24707
OBS1_sysb_max       25987
OBS1_sysb_min       25987
OBS2_sysb_max       24924
OBS2_sysb_min       24924
OBS1_diasb_max      25986
OBS1_diasb_min      25986
OBS2_diasb_max      24923
OBS2_diasb_min      24923
OBS1_temper_max     25124
OBS1_temper_min     25124
OBS2_temper_max     20061
OBS2_temper_min     20061
dtype: int64

In [229]:
rmd_v.dtypes

id                    int64
OBS1_hrate_max      float64
OBS1_hrate_min      float64
OBS2_hrate_max      float64
OBS2_hrate_min      float64
OBS1_reprate_max    float64
OBS1_reprate_min    float64
OBS2_reprate_max    float64
OBS2_reprate_min    float64
OBS1_sysb_max       float64
OBS1_sysb_min       float64
OBS2_sysb_max       float64
OBS2_sysb_min       float64
OBS1_diasb_max      float64
OBS1_diasb_min      float64
OBS2_diasb_max      float64
OBS2_diasb_min      float64
OBS1_temper_max     float64
OBS1_temper_min     float64
OBS2_temper_max     float64
OBS2_temper_min     float64
dtype: object

In [320]:
rmd_d = pd.read_csv('ramadan/data/Training/train_Demographics.csv')
rmd_l = pd.read_csv('ramadan/data/Training/train_Laboratory_Findings.csv')
rmd_m = pd.read_csv('ramadan/data/Training/train_Medical_History.csv')
rmd_t = pd.read_csv('ramadan/data/Training/train_Target_data.csv')
rmd_v = pd.read_csv('ramadan/data/Training/train_Vital_Signs.csv')

In [253]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,246060.0,77.0,Caucasian,F,70.2,160.0,27.421875
1,276985.0,25.0,Caucasian,F,95.3,172.7,31.952749
2,262220.0,81.0,Caucasian,F,61.7,165.1,22.635548
3,201746.0,19.0,Caucasian,M,NaN,188.0,NaN
4,182697.0,67.0,Caucasian,M,100.0,190.5,27.555611
...,...,...,...,...,...,...,...
104120,147574.0,50.0,African American,F,55.4,165.1,20.324301
104121,164758.0,50.0,Caucasian,M,90.0,175.3,29.287256
104122,197653.0,79.0,Caucasian,F,78.4,162.6,29.653433
104123,219719.0,73.0,African American,M,102.0,177.8,32.265371
104124,157942.0,35.0,African American,M,100.8,182.9,30.132358

In [258]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,246060.0,77.0,Caucasian,F,70.2,160.0,27.421875
1,276985.0,25.0,Caucasian,F,95.3,172.7,31.952749
2,262220.0,81.0,Caucasian,F,61.7,165.1,22.635548
4,182697.0,67.0,Caucasian,M,100.0,190.5,27.555611
5,195124.0,59.0,Caucasian,F,156.6,165.1,57.451002
...,...,...,...,...,...,...,...
104120,147574.0,50.0,African American,F,55.4,165.1,20.324301
104121,164758.0,50.0,Caucasian,M,90.0,175.3,29.287256
104122,197653.0,79.0,Caucasian,F,78.4,162.6,29.653433
104123,219719.0,73.0,African American,M,102.0,177.8,32.265371
104124,157942.0,35.0,African American,M,100.8,182.9,30.132358

In [260]:
rmd_d

,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hipanic,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown
0,246060.0,77.0,F,70.2,160.0,27.421875,False,False,False,True,False,False,False,False
1,276985.0,25.0,F,95.3,172.7,31.952749,False,False,False,True,False,False,False,False
2,262220.0,81.0,F,61.7,165.1,22.635548,False,False,False,True,False,False,False,False
4,182697.0,67.0,M,100.0,190.5,27.555611,False,False,False,True,False,False,False,False
5,195124.0,59.0,F,156.6,165.1,57.451002,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104120,147574.0,50.0,F,55.4,165.1,20.324301,False,True,False,False,False,False,False,False
104121,164758.0,50.0,M,90.0,175.3,29.287256,False,False,False,True,False,False,False,False
104122,197653.0,79.0,F,78.4,162.6,29.653433,False,False,False,True,False,False,False,False
104123,219719.0,73.0,M,102.0,177.8,32.265371,False,True,False,False,False,False,False,False
104124,157942.0,35.0,M,100.8,182.9,30.132358,False,True,False,False,False,False,False,False

In [337]:
rmd_d['gender_identity'].replace(['M','F'],[1,0])

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\716590103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rmd_d['gender_identity'].replace(['M','F'],[1,0],inplace=True)

In [262]:
rmd_d

,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hipanic,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown
0,246060.0,77.0,0,70.2,160.0,27.421875,False,False,False,True,False,False,False,False
1,276985.0,25.0,0,95.3,172.7,31.952749,False,False,False,True,False,False,False,False
2,262220.0,81.0,0,61.7,165.1,22.635548,False,False,False,True,False,False,False,False
4,182697.0,67.0,1,100.0,190.5,27.555611,False,False,False,True,False,False,False,False
5,195124.0,59.0,0,156.6,165.1,57.451002,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104120,147574.0,50.0,0,55.4,165.1,20.324301,False,True,False,False,False,False,False,False
104121,164758.0,50.0,1,90.0,175.3,29.287256,False,False,False,True,False,False,False,False
104122,197653.0,79.0,0,78.4,162.6,29.653433,False,False,False,True,False,False,False,False
104123,219719.0,73.0,1,102.0,177.8,32.265371,False,True,False,False,False,False,False,False
104124,157942.0,35.0,1,100.8,182.9,30.132358,False,True,False,False,False,False,False,False

In [338]:
rmd_d.corr()

ValueError: could not convert string to float: 'male'

In [339]:
value_to_search = 'male'
selected_columns = rmd_d.columns[rmd_d.eq(value_to_search).any()]
result_df = rmd_d[selected_columns]

In [340]:
rmd_d['gender_identity'].replace(['male','female'],[1,0],inplace = True )

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\3436056520.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  rmd_d['gender_identity'].replace(['male','female'],[1,0],inplace = True )

In [349]:
rmd_d.corr()

,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hipanic,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown
id,1.000000,0.000256,0.000414,0.004916,0.002619,0.003628,-0.003689,0.004624,-0.000165,-0.001591,-0.003075,0.000901,-0.001020,-0.001841
age_yrs,0.000256,1.000000,-0.028875,-0.124757,-0.113445,-0.082676,0.003063,-0.122049,0.000590,0.140568,-0.010510,-0.024618,-0.050373,-0.053193
gender_identity,0.000414,-0.028875,1.000000,0.236507,0.672674,-0.052134,-0.006798,-0.019960,-0.003969,0.007998,-0.001789,0.000628,-0.006373,0.015923
weight_kg,0.004916,-0.124757,0.236507,1.000000,0.378988,0.879377,-0.026810,0.048903,-0.084032,0.026812,-0.013907,-0.039712,0.012430,-0.038237
height_cm,0.002619,-0.113445,0.672674,0.378988,1.000000,-0.067894,-0.031345,0.032834,-0.080941,0.063721,-0.022059,-0.069151,-0.011556,-0.055988
body_mass_index,0.003628,-0.082676,-0.052134,0.879377,-0.067894,1.000000,-0.015910,0.041871,-0.057709,-0.002067,-0.005676,-0.011700,0.017846,-0.014986
ethnic_group_ASIAN,-0.003689,0.003063,-0.006798,-0.026810,-0.031345,-0.015910,1.000000,-0.014453,-0.005074,-0.075388,-0.002634,-0.007808,-0.003492,-0.009413
ethnic_group_African American,0.004624,-0.122049,-0.019960,0.048903,0.032834,0.041871,-0.014453,1.000000,-0.042907,-0.637470,-0.022275,-0.066021,-0.029528,-0.079598
ethnic_group_Asian,-0.000165,0.000590,-0.003969,-0.084032,-0.080941,-0.057709,-0.005074,-0.042907,1.000000,-0.223800,-0.007820,-0.023178,-0.010367,-0.027945
ethnic_group_Caucasian,-0.001591,0.140568,0.007998,0.026812,0.063721,-0.002067,-0.075388,-0.637470,-0.223800,1.000000,-0.116186,-0.344365,-0.154020,-0.415182
ethnic_group_Hipanic,-0.003075,-0.010510,-0.001789,-0.013907,-0.022059,-0.005676,-0.002634,-0.022275,-0.007820,-0.116186,1.000000,-0.012033,-0.005382,-0.014508
ethnic_group_Hispanic,0.000901,-0.024618,0.000628,-0.039712,-0.069151,-0.011700,-0.007808,-0.066021,-0.023178,-0.344365,-0.012033,1.000000,-0.015951,-0.042999
ethnic_group_Native American,-0.001020,-0.050373,-0.006373,0.012430,-0.011556,0.017846,-0.003492,-0.029528,-0.010367,-0.154020,-0.005382,-0.015951,1.000000,-0.019232
ethnic_group_Other/Unknown,-0.001841,-0.053193,0.015923,-0.038237,-0.055988,-0.014986,-0.009413,-0.079598,-0.027945,-0.415182,-0.014508,-0.042999,-0.019232,1.000000

In [589]:
rmd_l.drop(columns=['OBS2_bun_max','OBS2_bun_min','OBS2_sodium_max','OBS2_sodium_min'], inplace=True)

In [587]:
rmd_l.isna().sum()

id                         0
OBS1_albumin_max       57148
OBS1_albumin_min       57148
OBS2_albumin_min       95148
OBS1_bilirubin_max     61449
OBS1_bilirubin_min     61449
OBS1_bun_max           10969
OBS1_bun_min           10969
OBS2_bun_max           83897
OBS2_bun_min           83897
OBS1_creatinine_max    10597
OBS1_creatinine_min    10597
OBS2_creatinine_max    83750
OBS2_creatinine_min    83750
OBS1_glucose_max        6600
OBS1_glucose_min        6600
OBS2_glucose_max       60139
OBS2_glucose_min       60139
OBS1_hematocrit_max    12478
OBS1_hematocrit_min    12478
OBS2_hematocrit_max    82329
OBS2_hematocrit_min    82329
OBS1_sodium_max        10598
OBS1_sodium_min        10598
OBS2_sodium_max        81374
OBS2_sodium_min        81374
dtype: int64

In [352]:

rmd_m['liver_function_impaired'] =  rmd_m['liver_function_impaired'].replace('true',1.0)

C:\Users\asus\AppData\Local\Temp\ipykernel_49864\1874236338.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  rmd_m['liver_function_impaired'] =  rmd_m['liver_function_impaired'].replace('true',1.0)

rmd_m

In [353]:
rmd_m.corr()

,id,hiv_aids_status,chronic_liver_disease,liver_function_impaired,immune_compromise,blood_cancer,lymphatic_cancer,advanced_solid_tumor
id,1.000000,0.002594,-0.000201,-0.002675,0.000066,-0.001280,0.002974,0.007078
hiv_aids_status,0.002594,1.000000,0.009886,0.003633,0.018987,-0.002786,0.016135,-0.000604
chronic_liver_disease,-0.000201,0.009886,1.000000,0.533842,0.002628,-0.003666,0.000028,-0.002947
liver_function_impaired,-0.002675,0.003633,0.533842,1.000000,0.002543,0.001442,-0.000100,0.006304
immune_compromise,0.000066,0.018987,0.002628,0.002543,1.000000,0.130107,0.099095,0.275562
blood_cancer,-0.001280,-0.002786,-0.003666,0.001442,0.130107,1.000000,0.029645,0.009948
lymphatic_cancer,0.002974,0.016135,0.000028,-0.000100,0.099095,0.029645,1.000000,0.018866
advanced_solid_tumor,0.007078,-0.000604,-0.002947,0.006304,0.275562,0.009948,0.018866,1.000000

In [321]:
rmd_t

            id  fasting_ability
0       246060                0
1       276985                1
2       262220                1
3       201746                1
4       182697                0
...        ...              ...
104120  147574                1
104121  164758                1
104122  197653                1
104123  219719                0
104124  157942                1

[104125 rows x 2 columns]

In [354]:
rmd_v

,id,OBS1_hrate_max,OBS1_hrate_min,OBS2_hrate_max,OBS2_hrate_min,OBS1_reprate_max,OBS1_reprate_min,OBS2_reprate_max,OBS2_reprate_min,OBS1_sysb_max,...,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min
0,246060,118.0,72.0,114.0,100.0,32.0,12.0,31.0,28.0,159.0,...,95.0,71.0,95.0,31.0,61.0,48.0,36.3,35.1,36.3,36.3
1,276985,96.0,68.0,96.0,78.0,21.0,8.0,20.0,16.0,148.0,...,148.0,124.0,88.0,48.0,88.0,58.0,37.0,36.7,36.7,36.7
2,262220,116.0,92.0,100.0,96.0,23.0,7.0,12.0,11.0,158.0,...,136.0,106.0,48.0,42.0,62.0,44.0,38.0,34.8,35.6,34.8
3,201746,89.0,60.0,89.0,76.0,18.0,16.0,NaN,NaN,147.0,...,130.0,120.0,99.0,57.0,99.0,68.0,37.2,36.7,NaN,NaN
4,182697,113.0,83.0,83.0,83.0,32.0,10.0,12.0,12.0,173.0,...,143.0,143.0,100.0,61.0,89.0,89.0,36.8,36.6,36.7,36.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104120,147574,104.0,48.0,72.0,65.0,28.0,14.0,17.0,14.0,155.0,...,113.0,111.0,72.0,52.0,62.0,55.0,37.8,34.9,NaN,NaN
104121,164758,101.0,89.0,101.0,89.0,40.0,12.0,40.0,22.0,161.0,...,161.0,134.0,102.0,82.0,102.0,82.0,36.6,36.2,36.6,36.6
104122,197653,101.0,78.0,96.0,94.0,37.0,20.0,28.0,25.0,164.0,...,147.0,139.0,97.0,63.0,83.0,81.0,37.4,36.4,37.4,37.4
104123,219719,101.0,58.0,101.0,92.0,34.0,12.0,24.0,24.0,156.0,...,134.0,134.0,82.0,60.0,70.0,70.0,35.1,32.5,34.2,33.7
104124,157942,97.0,71.0,97.0,89.0,35.0,13.0,35.0,25.0,143.0,...,143.0,127.0,91.0,75.0,86.0,83.0,37.1,37.1,37.1,37.1

In [355]:
merged_df = pd.merge(rmd_t , rmd_d , rmd_l , rmd_m , rmd_v, on='id', how='inner')

TypeError: merge() got multiple values for argument 'on'

In [590]:
merged_df = pd.merge(rmd_t, rmd_d, on='id', how='inner')
merged_df = pd.merge(merged_df, rmd_l, on='id', how='inner')
merged_df = pd.merge(merged_df, rmd_m, on='id', how='inner')
merged_df = pd.merge(merged_df, rmd_v, on='id', how='inner')

In [359]:
merged_df.corr()

,id,fasting_ability,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,...,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min
id,1.000000,0.002734,0.000256,0.000414,0.004916,0.002619,0.003628,-0.003689,0.004624,-0.000165,...,0.000210,0.002704,0.001030,0.001883,-0.001658,-0.000326,-0.000477,0.003478,0.001538,0.001002
fasting_ability,0.002734,1.000000,-0.081174,-0.004269,-0.151716,0.008178,-0.166224,-0.001045,-0.038548,-0.007545,...,-0.044840,-0.025593,0.021008,0.056769,0.049986,0.066214,0.010609,0.007059,0.005500,0.007598
age_yrs,0.000256,-0.081174,1.000000,-0.028875,-0.124757,-0.113445,-0.082676,0.003063,-0.122049,0.000590,...,0.043753,-0.012393,-0.058023,-0.216100,-0.145723,-0.203316,-0.084750,-0.067280,-0.085625,-0.087642
gender_identity,0.000414,-0.004269,-0.028875,1.000000,0.236507,0.672674,-0.052134,-0.006798,-0.019960,-0.003969,...,0.008694,0.016546,0.023278,0.134309,0.063840,0.104508,0.017756,-0.004582,0.000422,-0.000643
weight_kg,0.004916,-0.151716,-0.124757,0.236507,1.000000,0.378988,0.879377,-0.026810,0.048903,-0.084032,...,0.060625,0.055516,0.062470,0.046748,0.057655,0.051422,0.027242,0.032511,0.037277,0.042421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OBS2_diasb_min,-0.000326,0.066214,-0.203316,0.104508,0.051422,0.111048,0.002395,-0.006306,0.120094,-0.009973,...,0.458223,0.679980,0.356542,0.612637,0.625057,1.000000,-0.082015,0.077784,0.023377,0.061614
OBS1_temper_max,-0.000477,0.010609,-0.084750,0.017756,0.027242,0.012895,0.021970,-0.004091,-0.015410,0.004653,...,-0.016703,-0.077665,0.008454,-0.097536,-0.021504,-0.082015,1.000000,0.254658,0.474244,0.394654
OBS1_temper_min,0.003478,0.007059,-0.067280,-0.004582,0.032511,0.002618,0.032463,-0.000165,-0.018846,-0.000774,...,0.033959,0.104675,-0.008637,0.104110,0.008968,0.077784,0.254658,1.000000,0.571966,0.648942
OBS2_temper_max,0.001538,0.005500,-0.085625,0.000422,0.037277,0.006017,0.036922,-0.003424,-0.017776,-0.002460,...,0.027981,0.039857,0.036338,0.024493,0.022513,0.023377,0.474244,0.571966,1.000000,0.859351
OBS2_temper_min,0.001002,0.007598,-0.087642,-0.000643,0.042421,0.005641,0.042461,0.000545,-0.009274,-0.003313,...,0.032107,0.076652,0.044218,0.047711,0.028398,0.061614,0.394654,0.648942,0.859351,1.000000

In [332]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,246060.0,77.0,Caucasian,F,70.2,160.0,27.421875
1,276985.0,25.0,Caucasian,F,95.3,172.7,31.952749
2,262220.0,81.0,Caucasian,F,61.7,165.1,22.635548
3,201746.0,19.0,Caucasian,M,NaN,188.0,NaN
4,182697.0,67.0,Caucasian,M,100.0,190.5,27.555611
...,...,...,...,...,...,...,...
104120,147574.0,50.0,African American,F,55.4,165.1,20.324301
104121,164758.0,50.0,Caucasian,M,90.0,175.3,29.287256
104122,197653.0,79.0,Caucasian,F,78.4,162.6,29.653433
104123,219719.0,73.0,African American,M,102.0,177.8,32.265371
104124,157942.0,35.0,African American,M,100.8,182.9,30.132358

In [333]:
rmd_t

            id  fasting_ability
0       246060                0
1       276985                1
2       262220                1
3       201746                1
4       182697                0
...        ...              ...
104120  147574                1
104121  164758                1
104122  197653                1
104123  219719                0
104124  157942                1

[104125 rows x 2 columns]

In [334]:
rmd_m

,id,hiv_aids_status,chronic_liver_disease,liver_function_impaired,immune_compromise,blood_cancer,lymphatic_cancer,advanced_solid_tumor
0,246060.0,0.0,0.0,0,0.0,0.0,0.0,0.0
1,276985.0,0.0,0.0,0,0.0,0.0,0.0,0.0
2,262220.0,0.0,0.0,0,0.0,0.0,0.0,0.0
3,201746.0,0.0,0.0,0,0.0,0.0,0.0,0.0
4,182697.0,0.0,0.0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
104120,147574.0,0.0,0.0,0,0.0,0.0,0.0,0.0
104121,164758.0,0.0,0.0,0,0.0,0.0,0.0,0.0
104122,197653.0,0.0,0.0,0,0.0,0.0,0.0,0.0
104123,219719.0,0.0,0.0,0,0.0,0.0,0.0,0.0
104124,157942.0,0.0,0.0,0,0.0,0.0,0.0,0.0

In [335]:
rmd_d

,id,age_yrs,ethnic_group,gender_identity,weight_kg,height_cm,body_mass_index
0,246060.0,77.0,Caucasian,F,70.2,160.0,27.421875
1,276985.0,25.0,Caucasian,F,95.3,172.7,31.952749
2,262220.0,81.0,Caucasian,F,61.7,165.1,22.635548
3,201746.0,19.0,Caucasian,M,NaN,188.0,NaN
4,182697.0,67.0,Caucasian,M,100.0,190.5,27.555611
...,...,...,...,...,...,...,...
104120,147574.0,50.0,African American,F,55.4,165.1,20.324301
104121,164758.0,50.0,Caucasian,M,90.0,175.3,29.287256
104122,197653.0,79.0,Caucasian,F,78.4,162.6,29.653433
104123,219719.0,73.0,African American,M,102.0,177.8,32.265371
104124,157942.0,35.0,African American,M,100.8,182.9,30.132358

In [591]:
merged_df.to_csv('rmd_final.csv')

In [362]:
merged_df

,id,fasting_ability,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,...,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min
0,246060,0,77.0,0.0,70.2,160.0,27.421875,False,False,False,...,95.0,71.0,95.0,31.0,61.0,48.0,36.3,35.1,36.3,36.3
1,276985,1,25.0,0.0,95.3,172.7,31.952749,False,False,False,...,148.0,124.0,88.0,48.0,88.0,58.0,37.0,36.7,36.7,36.7
2,262220,1,81.0,0.0,61.7,165.1,22.635548,False,False,False,...,136.0,106.0,48.0,42.0,62.0,44.0,38.0,34.8,35.6,34.8
3,182697,0,67.0,1.0,100.0,190.5,27.555611,False,False,False,...,143.0,143.0,100.0,61.0,89.0,89.0,36.8,36.6,36.7,36.7
4,195124,0,59.0,0.0,156.6,165.1,57.451002,False,False,False,...,191.0,163.0,76.0,68.0,107.0,79.0,37.2,35.0,36.8,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96694,147574,1,50.0,0.0,55.4,165.1,20.324301,False,True,False,...,113.0,111.0,72.0,52.0,62.0,55.0,37.8,34.9,NaN,NaN
96695,164758,1,50.0,1.0,90.0,175.3,29.287256,False,False,False,...,161.0,134.0,102.0,82.0,102.0,82.0,36.6,36.2,36.6,36.6
96696,197653,1,79.0,0.0,78.4,162.6,29.653433,False,False,False,...,147.0,139.0,97.0,63.0,83.0,81.0,37.4,36.4,37.4,37.4
96697,219719,0,73.0,1.0,102.0,177.8,32.265371,False,True,False,...,134.0,134.0,82.0,60.0,70.0,70.0,35.1,32.5,34.2,33.7
96698,157942,1,35.0,1.0,100.8,182.9,30.132358,False,True,False,...,143.0,127.0,91.0,75.0,86.0,83.0,37.1,37.1,37.1,37.1

In [363]:
rmd_l

,id,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_max,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS2_bilirubin_max,OBS2_bilirubin_min,OBS1_bun_max,...,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min
0,246060,1.6,1.6,NaN,NaN,0.5,0.5,NaN,NaN,11.0,...,145.0,143.0,36.9,36.1,36.9,36.9,145.0,145.0,145.0,145.0
1,276985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,262220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,34.0,25.9,34.0,34.0,NaN,NaN,NaN,NaN
3,201746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,182697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,...,NaN,NaN,44.2,44.2,NaN,NaN,137.0,137.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104120,147574,2.8,2.8,2.8,2.8,0.2,0.2,0.2,0.2,8.0,...,182.0,167.0,26.0,26.0,26.0,26.0,143.0,140.0,143.0,143.0
104121,164758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104122,197653,3.5,3.5,NaN,NaN,0.7,0.7,NaN,NaN,32.0,...,NaN,NaN,39.0,39.0,NaN,NaN,140.0,140.0,NaN,NaN
104123,219719,3.3,3.3,3.3,3.3,0.5,0.5,0.5,0.5,31.0,...,NaN,NaN,33.0,31.0,33.0,33.0,142.0,139.0,NaN,NaN
104124,157942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,...,100.0,100.0,NaN,NaN,NaN,NaN,135.0,135.0,135.0,135.0

In [364]:
rmd_l.isnull().sum()

id                         0
OBS1_albumin_max       57148
OBS1_albumin_min       57148
OBS2_albumin_max       95148
OBS2_albumin_min       95148
OBS1_bilirubin_max     61449
OBS1_bilirubin_min     61449
OBS2_bilirubin_max     95846
OBS2_bilirubin_min     95846
OBS1_bun_max           10969
OBS1_bun_min           10969
OBS2_bun_max           83897
OBS2_bun_min           83897
OBS1_creatinine_max    10597
OBS1_creatinine_min    10597
OBS2_creatinine_max    83750
OBS2_creatinine_min    83750
OBS1_glucose_max        6600
OBS1_glucose_min        6600
OBS2_glucose_max       60139
OBS2_glucose_min       60139
OBS1_hematocrit_max    12478
OBS1_hematocrit_min    12478
OBS2_hematocrit_max    82329
OBS2_hematocrit_min    82329
OBS1_sodium_max        10598
OBS1_sodium_min        10598
OBS2_sodium_max        81374
OBS2_sodium_min        81374
dtype: int64

In [592]:
merged_df_filled = merged_df.fillna(merged_df.mean())

,id,fasting_ability,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,...,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min
0,246060,0,77.0,0.0,70.2,160.0,27.421875,False,False,False,...,95.0,71.0,95.0,31.0,61.0,48.0,36.3,35.1,36.3,36.3
1,276985,1,25.0,0.0,95.3,172.7,31.952749,False,False,False,...,148.0,124.0,88.0,48.0,88.0,58.0,37.0,36.7,36.7,36.7
2,262220,1,81.0,0.0,61.7,165.1,22.635548,False,False,False,...,136.0,106.0,48.0,42.0,62.0,44.0,38.0,34.8,35.6,34.8
3,182697,0,67.0,1.0,100.0,190.5,27.555611,False,False,False,...,143.0,143.0,100.0,61.0,89.0,89.0,36.8,36.6,36.7,36.7
4,195124,0,59.0,0.0,156.6,165.1,57.451002,False,False,False,...,191.0,163.0,76.0,68.0,107.0,79.0,37.2,35.0,36.8,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96694,147574,1,50.0,0.0,55.4,165.1,20.324301,False,True,False,...,113.0,111.0,72.0,52.0,62.0,55.0,37.8,34.9,36.7,36.7
96695,164758,1,50.0,1.0,90.0,175.3,29.287256,False,False,False,...,161.0,134.0,102.0,82.0,102.0,82.0,36.6,36.2,36.6,36.6
96696,197653,1,79.0,0.0,78.4,162.6,29.653433,False,False,False,...,147.0,139.0,97.0,63.0,83.0,81.0,37.4,36.4,37.4,37.4
96697,219719,0,73.0,1.0,102.0,177.8,32.265371,False,True,False,...,134.0,134.0,82.0,60.0,70.0,70.0,35.1,32.5,34.2,33.7
96698,157942,1,35.0,1.0,100.8,182.9,30.132358,False,True,False,...,143.0,127.0,91.0,75.0,86.0,83.0,37.1,37.1,37.1,37.1

In [593]:
first_column = merged_df_filled['fasting_ability']
del  merged_df_filled['fasting_ability']

In [597]:
merged_df_filled.dtypes

id                                 int64
age_yrs                          float64
gender_identity                  float64
weight_kg                        float64
height_cm                        float64
body_mass_index                  float64
ethnic_group_ASIAN                  bool
ethnic_group_African American       bool
ethnic_group_Asian                  bool
ethnic_group_Caucasian              bool
ethnic_group_Hipanic                bool
ethnic_group_Hispanic               bool
ethnic_group_Native American        bool
ethnic_group_Other/Unknown          bool
OBS1_albumin_max                 float64
OBS1_albumin_min                 float64
OBS2_albumin_min                 float64
OBS1_bilirubin_max               float64
OBS1_bilirubin_min               float64
OBS1_bun_max                     float64
OBS1_bun_min                     float64
OBS1_creatinine_max              float64
OBS1_creatinine_min              float64
OBS2_creatinine_max              float64
OBS2_creatinine_min              float64
OBS1_glucose_max                 float64
OBS1_glucose_min                 float64
OBS2_glucose_max                 float64
OBS2_glucose_min                 float64
OBS1_hematocrit_max              float64
OBS1_hematocrit_min              float64
OBS2_hematocrit_max              float64
OBS2_hematocrit_min              float64
OBS1_sodium_max                  float64
OBS1_sodium_min                  float64
hiv_aids_status                  float64
chronic_liver_disease            float64
liver_function_impaired          float64
immune_compromise                float64
blood_cancer                     float64
lymphatic_cancer                 float64
advanced_solid_tumor             float64
OBS1_hrate_max                   float64
OBS1_hrate_min                   float64
OBS2_hrate_max                   float64
OBS2_hrate_min                   float64
OBS1_reprate_max                 float64
OBS1_reprate_min                 float64
OBS2_reprate_max                 float64
OBS2_reprate_min                 float64
OBS1_sysb_max                    float64
OBS1_sysb_min                    float64
OBS2_sysb_max                    float64
OBS2_sysb_min                    float64
OBS1_diasb_max                   float64
OBS1_diasb_min                   float64
OBS2_diasb_max                   float64
OBS2_diasb_min                   float64
OBS1_temper_max                  float64
OBS1_temper_min                  float64
OBS2_temper_max                  float64
OBS2_temper_min                  float64
fasting_ability                    int64
dtype: object

In [595]:
merged_df_filled.to_csv('rmd_final4.csv')

In [523]:
merge = pd.read_csv('merged.csv')

In [401]:
merge

,Unnamed: 0,loanId,anon_ssn,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanStatus,...,paymentReturnCode_R16,paymentReturnCode_R20,paymentReturnCode_R29,paymentReturnCode_R99,paymentReturnCode_RAF,paymentReturnCode_RBW,paymentReturnCode_RUP,paymentReturnCode_RWC,paymentReturnCode_RXL,paymentReturnCode_RXS
0,0,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264984,264984,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
264985,264985,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
264986,264986,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
264987,264987,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
264988,264988,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [477]:
pd.set_option('display.max_columns',200)

In [526]:

merge.select_dtypes(include='int').fillna(merge.select_dtypes(include='int').mean(),inplace=True)

In [470]:
merge

,Unnamed: 0,loanId,anon_ssn,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,leadCost,clarityFraudId,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_express,leadType_instant-offer,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,leadType_repeat,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,state_AK,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MD,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NE,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_RI,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Complete,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Rejected Awaiting Retry,paymentStatus_Returned,paymentStatus_Skipped,paymentReturnCode_C01,paymentReturnCode_C02,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_LPP01,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R06,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R13,paymentReturnCode_R15,paymentReturnCode_R16,paymentReturnCode_R20,paymentReturnCode_R29,paymentReturnCode_R99,paymentReturnCode_RAF,paymentReturnCode_RBW,paymentReturnCode_RUP,paymentReturnCode_RWC,paymentReturnCode_RXL,paymentReturnCode_RXS
0,0,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2016-01-27 05:00:00,151.98,114.49,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2016-02-10 05:00:00,49.08,217.39,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,2016-02-24 05:00:00,52.83,213.64,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,2016-03-09 05:00:00,56.86,209.61,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,2016-03-23 04:00:00,61.20,205.27,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264984,264984,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,2017-05-25 04:00:00,21.85,17.38,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264985,264985,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,0,2017-06-01 04:00:00,24.56,14.67,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264986,264986,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,0,2017-06-08 04:00:00,27.59,11.64,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264987,264987,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,2017-06-15 04:00:00,31.01,8.22,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264988,264988,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,2017-06-22 04:00:00,35.46,4.39,39.85,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [527]:
pd.DataFrame(merge_cleaned.isna().sum())

                                           0
Unnamed: 0                                 0
loanId                                     0
anon_ssn                                   0
apr                                        0
applicationDate                          188
originatedDate                           204
nPaidOff                                  82
approved                                 188
isFunded                                   0
loanStatus                                 0
loanAmount                                 0
originallyScheduledPaymentAmount           0
leadCost                                   0
clarityFraudId                             0
hasCF                                      0
payFrequency_B                             0
payFrequency_I                             0
payFrequency_M                             0
payFrequency_S                             0
payFrequency_W                             0
leadType_bvMandatory                       0
leadType_california                        0
leadType_express                           0
leadType_instant-offer                     0
leadType_lead                              0
leadType_lionpay                           0
leadType_organic                           0
leadType_prescreen                         0
leadType_rc_returning                      0
leadType_repeat                            0
fpStatus_Cancelled                         0
fpStatus_Checked                           0
fpStatus_Rejected                          0
fpStatus_Skipped                           0
state_AK                                   0
state_AL                                   0
state_AZ                                   0
state_CA                                   0
state_CO                                   0
state_CT                                   0
state_DE                                   0
state_FL                                   0
state_GA                                   0
state_HI                                   0
state_IA                                   0
state_ID                                   0
state_IL                                   0
state_IN                                   0
state_KS                                   0
state_KY                                   0
state_LA                                   0
state_MD                                   0
state_MI                                   0
state_MN                                   0
state_MO                                   0
state_MS                                   0
state_NC                                   0
state_ND                                   0
state_NE                                   0
state_NJ                                   0
state_NM                                   0
state_NV                                   0
state_OH                                   0
state_OK                                   0
state_PA                                   0
state_RI                                   0
state_SC                                   0
state_SD                                   0
state_TN                                   0
state_TX                                   0
state_UT                                   0
state_VA                                   0
state_WA                                   0
state_WI                                   0
state_WY                                   0
installmentIndex                           0
isCollection                               0
paymentDate                            10748
principal                                  0
fees                                       0
paymentAmount                              0
paymentStatus_Cancelled                    0
paymentStatus_Checked                      0
paymentStatus_Complete                     0
paymentStatus_Pending                      0
paymentStatus_Rejected                     0
paymentStatus_Rejected Awaiting Retry      0
paymentStatus_Returned                     0
paymentStatus_Skipped                      0
paymentReturnCode_C01                      0
paymentReturnCode_C02                      0
paymentReturnCode_C03                      0
paymentReturnCode_C05                      0
paymentReturnCode_LPP01                    0
paymentReturnCode_MISSED                   0
paymentReturnCode_R01                      0
paymentReturnCode_R02                      0
paymentReturnCode_R03                      0
paymentReturnCode_R04                      0
paymentReturnCode_R06                      0
paymentReturnCode_R07                      0
paymentReturnCode_R08                      0
paymentReturnCode_R09                      0
paymentReturnCode_R10                      0
paymentReturnCode_R13                      0
paymentReturnCode_R15                      0
paymentReturnCode_R16                      0
paymentReturnCode_R20                      0
paymentReturnCode_R29                      0
paymentReturnCode_R99                      0
paymentReturnCode_RAF                      0
paymentReturnCode_RBW                      0
paymentReturnCode_RUP                      0
paymentReturnCode_RWC                      0
paymentReturnCode_RXL                      0
paymentReturnCode_RXS                      0

In [528]:
merge_cleaned = merge

In [545]:
merge_cleaned.isna().sum()

Unnamed: 0                                   0
loanId                                       0
anon_ssn                                     0
apr                                          0
applicationDate                            188
originatedDate                             204
nPaidOff                                    82
approved                                     0
isFunded                                     0
loanStatus                                   0
loanAmount                                   0
originallyScheduledPaymentAmount             0
leadCost                                     0
clarityFraudId                               0
hasCF                                        0
payFrequency_B                               0
payFrequency_I                               0
payFrequency_M                               0
payFrequency_S                               0
payFrequency_W                               0
leadType_bvMandatory                         0
leadType_california                          0
leadType_express                             0
leadType_instant-offer                       0
leadType_lead                                0
leadType_lionpay                             0
leadType_organic                             0
leadType_prescreen                           0
leadType_rc_returning                        0
leadType_repeat                              0
fpStatus_Cancelled                           0
fpStatus_Checked                             0
fpStatus_Rejected                            0
fpStatus_Skipped                             0
state_AK                                     0
state_AL                                     0
state_AZ                                     0
state_CA                                     0
state_CO                                     0
state_CT                                     0
state_DE                                     0
state_FL                                     0
state_GA                                     0
state_HI                                     0
state_IA                                     0
state_ID                                     0
state_IL                                     0
state_IN                                     0
state_KS                                     0
state_KY                                     0
state_LA                                     0
state_MD                                     0
state_MI                                     0
state_MN                                     0
state_MO                                     0
state_MS                                     0
state_NC                                     0
state_ND                                     0
state_NE                                     0
state_NJ                                     0
state_NM                                     0
state_NV                                     0
state_OH                                     0
state_OK                                     0
state_PA                                     0
state_RI                                     0
state_SC                                     0
state_SD                                     0
state_TN                                     0
state_TX                                     0
state_UT                                     0
state_VA                                     0
state_WA                                     0
state_WI                                     0
state_WY                                     0
installmentIndex                             0
isCollection                                 0
paymentDate                              10748
principal                                    0
fees                                         0
paymentAmount                                0
paymentStatus_Cancelled                      0
paymentStatus_Checked                        0
paymentStatus_Complete                       0
paymentStatus_Pending                        0
paymentStatus_Rejected                       0
paymentStatus_Rejected Awaiting Retry        0
paymentStatus_Returned                       0
paymentStatus_Skipped                        0
paymentReturnCode_C01                        0
paymentReturnCode_C02                        0
paymentReturnCode_C03                        0
paymentReturnCode_C05                        0
paymentReturnCode_LPP01                      0
paymentReturnCode_MISSED                     0
paymentReturnCode_R01                        0
paymentReturnCode_R02                        0
paymentReturnCode_R03                        0
paymentReturnCode_R04                        0
paymentReturnCode_R06                        0
paymentReturnCode_R07                        0
paymentReturnCode_R08                        0
paymentReturnCode_R09                        0
paymentReturnCode_R10                        0
paymentReturnCode_R13                        0
paymentReturnCode_R15                        0
paymentReturnCode_R16                        0
paymentReturnCode_R20                        0
paymentReturnCode_R29                        0
paymentReturnCode_R99                        0
paymentReturnCode_RAF                        0
paymentReturnCode_RBW                        0
paymentReturnCode_RUP                        0
paymentReturnCode_RWC                        0
paymentReturnCode_RXL                        0
paymentReturnCode_RXS                        0
dtype: int64

In [548]:
merge.dropna(subset=['applicationDate','originatedDate','nPaidOff','paymentDate'],how='any',inplace = True)

In [497]:
filt ='applicationDate' , 'originatedDate' , 'originatedDate' , 'originatedDate'

originatedDate
False    264597
True        392
Name: count, dtype: int64

In [537]:
merge_cleaned['applicationDate'] = merge_cleaned['applicationDate'][~filt]

In [596]:
merge_cleaned.dtypes

Unnamed: 0                                        int64
apr                                             float64
applicationDate                          datetime64[ns]
originatedDate                           datetime64[ns]
nPaidOff                                        float64
isFunded                                          int64
loanStatus                                        int64
loanAmount                                      float64
originallyScheduledPaymentAmount                float64
leadCost                                          int64
hasCF                                             int64
payFrequency_B                                    int64
payFrequency_I                                    int64
payFrequency_M                                    int64
payFrequency_S                                    int64
payFrequency_W                                    int64
leadType_bvMandatory                              int64
leadType_california                               int64
leadType_express                                  int64
leadType_lead                                     int64
leadType_lionpay                                  int64
leadType_organic                                  int64
leadType_prescreen                                int64
leadType_rc_returning                             int64
leadType_repeat                                   int64
fpStatus_Cancelled                                int64
fpStatus_Checked                                  int64
fpStatus_Rejected                                 int64
fpStatus_Skipped                                  int64
state_AK                                          int64
state_AL                                          int64
state_AZ                                          int64
state_CA                                          int64
state_CO                                          int64
state_CT                                          int64
state_DE                                          int64
state_FL                                          int64
state_GA                                          int64
state_HI                                          int64
state_IA                                          int64
state_ID                                          int64
state_IL                                          int64
state_IN                                          int64
state_KS                                          int64
state_KY                                          int64
state_LA                                          int64
state_MD                                          int64
state_MI                                          int64
state_MN                                          int64
state_MO                                          int64
state_MS                                          int64
state_NC                                          int64
state_ND                                          int64
state_NE                                          int64
state_NJ                                          int64
state_NM                                          int64
state_NV                                          int64
state_OH                                          int64
state_OK                                          int64
state_PA                                          int64
state_RI                                          int64
state_SC                                          int64
state_SD                                          int64
state_TN                                          int64
state_TX                                          int64
state_UT                                          int64
state_VA                                          int64
state_WA                                          int64
state_WI                                          int64
state_WY                                          int64
installmentIndex                                  int64
isCollection                                      int64
paymentDate                              datetime64[ns]
principal                                       float64
fees                                            float64
paymentAmount                                   float64
paymentStatus_Cancelled                           int64
paymentStatus_Checked                             int64
paymentStatus_Complete                            int64
paymentStatus_Pending                             int64
paymentStatus_Rejected                            int64
paymentStatus_Rejected Awaiting Retry             int64
paymentStatus_Skipped                             int64
paymentReturnCode_C01                             int64
paymentReturnCode_C02                             int64
paymentReturnCode_C03                             int64
paymentReturnCode_C05                             int64
paymentReturnCode_LPP01                           int64
paymentReturnCode_MISSED                          int64
paymentReturnCode_R01                             int64
paymentReturnCode_R02                             int64
paymentReturnCode_R03                             int64
paymentReturnCode_R04                             int64
paymentReturnCode_R06                             int64
paymentReturnCode_R07                             int64
paymentReturnCode_R08                             int64
paymentReturnCode_R09                             int64
paymentReturnCode_R10                             int64
paymentReturnCode_R13                             int64
paymentReturnCode_R15                             int64
paymentReturnCode_R16                             int64
paymentReturnCode_R20                             int64
paymentReturnCode_R29                             int64
paymentReturnCode_R99                             int64
paymentReturnCode_RAF                             int64
paymentReturnCode_RBW                             int64
paymentReturnCode_RUP                             int64
paymentReturnCode_RWC                             int64
paymentReturnCode_RXL                             int64
paymentReturnCode_RXS                             int64
dtype: object

In [549]:
merge.isna().sum()

Unnamed: 0                               0
loanId                                   0
anon_ssn                                 0
apr                                      0
applicationDate                          0
originatedDate                           0
nPaidOff                                 0
approved                                 0
isFunded                                 0
loanStatus                               0
loanAmount                               0
originallyScheduledPaymentAmount         0
leadCost                                 0
clarityFraudId                           0
hasCF                                    0
payFrequency_B                           0
payFrequency_I                           0
payFrequency_M                           0
payFrequency_S                           0
payFrequency_W                           0
leadType_bvMandatory                     0
leadType_california                      0
leadType_express                         0
leadType_instant-offer                   0
leadType_lead                            0
leadType_lionpay                         0
leadType_organic                         0
leadType_prescreen                       0
leadType_rc_returning                    0
leadType_repeat                          0
fpStatus_Cancelled                       0
fpStatus_Checked                         0
fpStatus_Rejected                        0
fpStatus_Skipped                         0
state_AK                                 0
state_AL                                 0
state_AZ                                 0
state_CA                                 0
state_CO                                 0
state_CT                                 0
state_DE                                 0
state_FL                                 0
state_GA                                 0
state_HI                                 0
state_IA                                 0
state_ID                                 0
state_IL                                 0
state_IN                                 0
state_KS                                 0
state_KY                                 0
state_LA                                 0
state_MD                                 0
state_MI                                 0
state_MN                                 0
state_MO                                 0
state_MS                                 0
state_NC                                 0
state_ND                                 0
state_NE                                 0
state_NJ                                 0
state_NM                                 0
state_NV                                 0
state_OH                                 0
state_OK                                 0
state_PA                                 0
state_RI                                 0
state_SC                                 0
state_SD                                 0
state_TN                                 0
state_TX                                 0
state_UT                                 0
state_VA                                 0
state_WA                                 0
state_WI                                 0
state_WY                                 0
installmentIndex                         0
isCollection                             0
paymentDate                              0
principal                                0
fees                                     0
paymentAmount                            0
paymentStatus_Cancelled                  0
paymentStatus_Checked                    0
paymentStatus_Complete                   0
paymentStatus_Pending                    0
paymentStatus_Rejected                   0
paymentStatus_Rejected Awaiting Retry    0
paymentStatus_Returned                   0
paymentStatus_Skipped                    0
paymentReturnCode_C01                    0
paymentReturnCode_C02                    0
paymentReturnCode_C03                    0
paymentReturnCode_C05                    0
paymentReturnCode_LPP01                  0
paymentReturnCode_MISSED                 0
paymentReturnCode_R01                    0
paymentReturnCode_R02                    0
paymentReturnCode_R03                    0
paymentReturnCode_R04                    0
paymentReturnCode_R06                    0
paymentReturnCode_R07                    0
paymentReturnCode_R08                    0
paymentReturnCode_R09                    0
paymentReturnCode_R10                    0
paymentReturnCode_R13                    0
paymentReturnCode_R15                    0
paymentReturnCode_R16                    0
paymentReturnCode_R20                    0
paymentReturnCode_R29                    0
paymentReturnCode_R99                    0
paymentReturnCode_RAF                    0
paymentReturnCode_RBW                    0
paymentReturnCode_RUP                    0
paymentReturnCode_RWC                    0
paymentReturnCode_RXL                    0
paymentReturnCode_RXS                    0
dtype: int64

In [551]:
merge

,Unnamed: 0,loanId,anon_ssn,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,leadCost,clarityFraudId,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_express,leadType_instant-offer,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,leadType_repeat,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,state_AK,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MD,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NE,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_RI,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Complete,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Rejected Awaiting Retry,paymentStatus_Returned,paymentStatus_Skipped,paymentReturnCode_C01,paymentReturnCode_C02,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_LPP01,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R06,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R13,paymentReturnCode_R15,paymentReturnCode_R16,paymentReturnCode_R20,paymentReturnCode_R29,paymentReturnCode_R99,paymentReturnCode_RAF,paymentReturnCode_RBW,paymentReturnCode_RUP,paymentReturnCode_RWC,paymentReturnCode_RXL,paymentReturnCode_RXS
0,0,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2016-01-27 05:00:00,151.98,114.49,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2016-02-10 05:00:00,49.08,217.39,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,2016-02-24 05:00:00,52.83,213.64,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,2016-03-09 05:00:00,56.86,209.61,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,2016-03-23 04:00:00,61.20,205.27,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264984,264984,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,2017-05-25 04:00:00,21.85,17.38,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264985,264985,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,0,2017-06-01 04:00:00,24.56,14.67,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264986,264986,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,0,2017-06-08 04:00:00,27.59,11.64,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264987,264987,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,2017-06-15 04:00:00,31.01,8.22,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264988,264988,LL-I-13311312,043dd86c24c63c8968082fa3ad7a8911,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,2017-06-22 04:00:00,35.46,4.39,39.85,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [556]:
merge.dtypes

Unnamed: 0                                 int64
apr                                      float64
applicationDate                           object
originatedDate                            object
nPaidOff                                 float64
approved                                   int64
isFunded                                   int64
loanStatus                                 int64
loanAmount                               float64
originallyScheduledPaymentAmount         float64
leadCost                                   int64
clarityFraudId                             int64
hasCF                                      int64
payFrequency_B                             int64
payFrequency_I                             int64
payFrequency_M                             int64
payFrequency_S                             int64
payFrequency_W                             int64
leadType_bvMandatory                       int64
leadType_california                        int64
leadType_express                           int64
leadType_instant-offer                     int64
leadType_lead                              int64
leadType_lionpay                           int64
leadType_organic                           int64
leadType_prescreen                         int64
leadType_rc_returning                      int64
leadType_repeat                            int64
fpStatus_Cancelled                         int64
fpStatus_Checked                           int64
fpStatus_Rejected                          int64
fpStatus_Skipped                           int64
state_AK                                   int64
state_AL                                   int64
state_AZ                                   int64
state_CA                                   int64
state_CO                                   int64
state_CT                                   int64
state_DE                                   int64
state_FL                                   int64
state_GA                                   int64
state_HI                                   int64
state_IA                                   int64
state_ID                                   int64
state_IL                                   int64
state_IN                                   int64
state_KS                                   int64
state_KY                                   int64
state_LA                                   int64
state_MD                                   int64
state_MI                                   int64
state_MN                                   int64
state_MO                                   int64
state_MS                                   int64
state_NC                                   int64
state_ND                                   int64
state_NE                                   int64
state_NJ                                   int64
state_NM                                   int64
state_NV                                   int64
state_OH                                   int64
state_OK                                   int64
state_PA                                   int64
state_RI                                   int64
state_SC                                   int64
state_SD                                   int64
state_TN                                   int64
state_TX                                   int64
state_UT                                   int64
state_VA                                   int64
state_WA                                   int64
state_WI                                   int64
state_WY                                   int64
installmentIndex                           int64
isCollection                               int64
paymentDate                               object
principal                                float64
fees                                     float64
paymentAmount                            float64
paymentStatus_Cancelled                    int64
paymentStatus_Checked                      int64
paymentStatus_Complete                     int64
paymentStatus_Pending                      int64
paymentStatus_Rejected                     int64
paymentStatus_Rejected Awaiting Retry      int64
paymentStatus_Returned                     int64
paymentStatus_Skipped                      int64
paymentReturnCode_C01                      int64
paymentReturnCode_C02                      int64
paymentReturnCode_C03                      int64
paymentReturnCode_C05                      int64
paymentReturnCode_LPP01                    int64
paymentReturnCode_MISSED                   int64
paymentReturnCode_R01                      int64
paymentReturnCode_R02                      int64
paymentReturnCode_R03                      int64
paymentReturnCode_R04                      int64
paymentReturnCode_R06                      int64
paymentReturnCode_R07                      int64
paymentReturnCode_R08                      int64
paymentReturnCode_R09                      int64
paymentReturnCode_R10                      int64
paymentReturnCode_R13                      int64
paymentReturnCode_R15                      int64
paymentReturnCode_R16                      int64
paymentReturnCode_R20                      int64
paymentReturnCode_R29                      int64
paymentReturnCode_R99                      int64
paymentReturnCode_RAF                      int64
paymentReturnCode_RBW                      int64
paymentReturnCode_RUP                      int64
paymentReturnCode_RWC                      int64
paymentReturnCode_RXL                      int64
paymentReturnCode_RXS                      int64
dtype: object

In [561]:
d.drop(columns =['loanId'	,'anon_ssn'],inplace=True)

KeyError: "['loanId', 'anon_ssn'] not found in axis"

In [558]:
merge['applicationDate'] = pd.to_datetime(merge['applicationDate'], errors='coerce')
merge['originatedDate'] = pd.to_datetime(merge['originatedDate'], errors='coerce')
merge['paymentDate'] = pd.to_datetime(merge['paymentDate'], errors='coerce')

In [565]:
merge

,Unnamed: 0,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,leadCost,clarityFraudId,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_express,leadType_instant-offer,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,leadType_repeat,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,state_AK,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MD,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NE,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_RI,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Complete,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Rejected Awaiting Retry,paymentStatus_Returned,paymentStatus_Skipped,paymentReturnCode_C01,paymentReturnCode_C02,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_LPP01,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R06,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R13,paymentReturnCode_R15,paymentReturnCode_R16,paymentReturnCode_R20,paymentReturnCode_R29,paymentReturnCode_R99,paymentReturnCode_RAF,paymentReturnCode_RBW,paymentReturnCode_RUP,paymentReturnCode_RWC,paymentReturnCode_RXL,paymentReturnCode_RXS
0,0,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2016-01-27 05:00:00,151.98,114.49,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2016-02-10 05:00:00,49.08,217.39,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,2016-02-24 05:00:00,52.83,213.64,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,2016-03-09 05:00:00,56.86,209.61,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,1,0,3000.0,6395.19,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,2016-03-23 04:00:00,61.20,205.27,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264984,264984,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,2017-05-25 04:00:00,21.85,17.38,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264985,264985,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,0,2017-06-01 04:00:00,24.56,14.67,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264986,264986,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,0,2017-06-08 04:00:00,27.59,11.64,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264987,264987,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,2017-06-15 04:00:00,31.01,8.22,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264988,264988,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,1,0,300.0,1034.38,6,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,2017-06-22 04:00:00,35.46,4.39,39.85,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [572]:
del merge['paymentStatus_Returned']

In [575]:
merge.to_csv('final_data.csv')

In [576]:
rmd = pd.read_csv('rmd_final4.csv')

In [577]:
rmd

,Unnamed: 0,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hipanic,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS1_bun_max,OBS1_bun_min,OBS2_bun_max,OBS2_bun_min,OBS1_creatinine_max,OBS1_creatinine_min,OBS2_creatinine_max,OBS2_creatinine_min,OBS1_glucose_max,OBS1_glucose_min,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min,hiv_aids_status,chronic_liver_disease,liver_function_impaired,immune_compromise,blood_cancer,lymphatic_cancer,advanced_solid_tumor,OBS1_hrate_max,OBS1_hrate_min,OBS2_hrate_max,OBS2_hrate_min,OBS1_reprate_max,OBS1_reprate_min,OBS2_reprate_max,OBS2_reprate_min,OBS1_sysb_max,OBS1_sysb_min,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min,fasting_ability
0,0,246060,77.0,0.0,70.2,160.0,27.421875,False,False,False,True,False,False,False,False,1.6,1.6,3.1,0.5,0.5,11.0,9.0,9.0,9.0,0.71,0.56,0.56,0.56,145.0,128.0,145.0,143.0,36.9,36.1,36.9,36.9,145.0,145.0,145.0,145.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.0,72.0,114.0,100.0,32.0,12.0,31.0,28.0,159.0,67.0,95.0,71.0,95.0,31.0,61.0,48.0,36.3,35.1,36.3,36.3,0
1,1,276985,25.0,0.0,95.3,172.7,31.952749,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,150.0,108.0,140.0,134.0,34.6,33.2,33.7,33.3,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,68.0,96.0,78.0,21.0,8.0,20.0,16.0,148.0,105.0,148.0,124.0,88.0,48.0,88.0,58.0,37.0,36.7,36.7,36.7,1
2,2,262220,81.0,0.0,61.7,165.1,22.635548,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,185.0,88.0,140.0,134.0,34.0,25.9,34.0,34.0,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116.0,92.0,100.0,96.0,23.0,7.0,12.0,11.0,158.0,84.0,136.0,106.0,48.0,42.0,62.0,44.0,38.0,34.8,35.6,34.8,1
3,3,182697,67.0,1.0,100.0,190.5,27.555611,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,13.0,13.0,18.0,18.0,0.71,0.71,1.00,1.00,156.0,125.0,140.0,134.0,44.2,44.2,33.7,33.3,137.0,137.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.0,83.0,83.0,83.0,32.0,10.0,12.0,12.0,173.0,107.0,143.0,143.0,100.0,61.0,89.0,89.0,36.8,36.6,36.7,36.7,0
4,4,195124,59.0,0.0,156.6,165.1,57.451002,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,11.0,18.0,18.0,0.85,0.78,0.78,0.78,197.0,129.0,197.0,194.0,37.5,33.5,33.5,33.5,136.0,135.0,135.0,135.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.0,70.0,79.0,72.0,38.0,16.0,18.0,18.0,151.0,133.0,191.0,163.0,76.0,68.0,107.0,79.0,37.2,35.0,36.8,35.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96694,96694,147574,50.0,0.0,55.4,165.1,20.324301,False,True,False,False,False,False,False,False,2.8,2.8,2.8,0.2,0.2,8.0,7.0,7.0,7.0,0.86,0.73,0.73,0.73,182.0,121.0,182.0,167.0,26.0,26.0,26.0,26.0,143.0,140.0,143.0,143.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.0,48.0,72.0,65.0,28.0,14.0,17.0,14.0,155.0,91.0,113.0,111.0,72.0,52.0,62.0,55.0,37.8,34.9,36.7,36.7,1
96695,96695,164758,50.0,1.0,90.0,175.3,29.287256,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,150.0,108.0,140.0,134.0,34.6,33.2,33.7,33.3,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,89.0,101.0,89.0,40.0,12.0,40.0,22.0,161.0,134.0,161.0,134.0,102.0,82.0,102.0,82.0,36.6,36.2,36.6,36.6,1
96696,96696,197653,79.0,0.0,78.4,162.6,29.653433,False,False,False,True,False,False,False,False,3.5,3.5,3.1,0.7,0.7,32.0,32.0,18.0,18.0,1.07,1.07,1.00,1.00,139.0,139.0,140.0,134.0,39.0,39.0,33.7,33.3,140.0,140.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,78.0,96.0,94.0,37.0,20.0,28.0,25.0,164.0,109.0,147.0,139.0,97.0,63.0,83.0,81.0,37.4,36.4,37.4,37.4,1
96697,96697,219719,73.0,1.0,102.0,177.8,32.265371,False,True,False,False,False,False,False,False,3.3,3.3,3.3,0.5,0.5,31.0,30.0,18.0,18.0,2.65,2.41,1.00,1.00,346.0,55.0,140.0,134.0,33.0,31.0,33.0,33.0,142.0,139.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,58.0,101.0,92.0,34.0,12.0,24.0,24.0,156.0,123.0,134.0,134.0,82.0,60.0,70.0,70.0,35.1,32.5,34.2,33.7,0
96698,96698,157942,35.0,1.0,100.8,182.9,30.132358,False,True,False,False,False,False,False,False,3.0,2.9,3.1,0.7,0.6,13.0,13.0,13.0,13.0,1.06,1.06,1.06,1.06,100.0,100.0,100.0,100.0,34.6,33.2,33.7,33.3,135.0,135.0,135.0,135.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0,71.0,97.0,89.0,35.0,13.0,35.0,25.0,143.0,116.0,143.0,127.0,91.0,75.0,86.0,83.0,37.1,37.1,37.1,37.1,1

In [584]:
rmd2 = rmd
rmd.drop(columns=['Unnamed: 0','gender_identity','id','weight_kg','height_cm'] inplice = True)
rmd2.tp_csv('rmd_final3.csv')

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1844885917.py, line 2)

In [585]:
rmd.to_csv('rmd_final3.csv')

In [586]:
rmd

,Unnamed: 0,id,age_yrs,gender_identity,weight_kg,height_cm,body_mass_index,ethnic_group_ASIAN,ethnic_group_African American,ethnic_group_Asian,ethnic_group_Caucasian,ethnic_group_Hipanic,ethnic_group_Hispanic,ethnic_group_Native American,ethnic_group_Other/Unknown,OBS1_albumin_max,OBS1_albumin_min,OBS2_albumin_min,OBS1_bilirubin_max,OBS1_bilirubin_min,OBS1_bun_max,OBS1_bun_min,OBS2_bun_max,OBS2_bun_min,OBS1_creatinine_max,OBS1_creatinine_min,OBS2_creatinine_max,OBS2_creatinine_min,OBS1_glucose_max,OBS1_glucose_min,OBS2_glucose_max,OBS2_glucose_min,OBS1_hematocrit_max,OBS1_hematocrit_min,OBS2_hematocrit_max,OBS2_hematocrit_min,OBS1_sodium_max,OBS1_sodium_min,OBS2_sodium_max,OBS2_sodium_min,hiv_aids_status,chronic_liver_disease,liver_function_impaired,immune_compromise,blood_cancer,lymphatic_cancer,advanced_solid_tumor,OBS1_hrate_max,OBS1_hrate_min,OBS2_hrate_max,OBS2_hrate_min,OBS1_reprate_max,OBS1_reprate_min,OBS2_reprate_max,OBS2_reprate_min,OBS1_sysb_max,OBS1_sysb_min,OBS2_sysb_max,OBS2_sysb_min,OBS1_diasb_max,OBS1_diasb_min,OBS2_diasb_max,OBS2_diasb_min,OBS1_temper_max,OBS1_temper_min,OBS2_temper_max,OBS2_temper_min,fasting_ability
0,0,246060,77.0,0.0,70.2,160.0,27.421875,False,False,False,True,False,False,False,False,1.6,1.6,3.1,0.5,0.5,11.0,9.0,9.0,9.0,0.71,0.56,0.56,0.56,145.0,128.0,145.0,143.0,36.9,36.1,36.9,36.9,145.0,145.0,145.0,145.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.0,72.0,114.0,100.0,32.0,12.0,31.0,28.0,159.0,67.0,95.0,71.0,95.0,31.0,61.0,48.0,36.3,35.1,36.3,36.3,0
1,1,276985,25.0,0.0,95.3,172.7,31.952749,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,150.0,108.0,140.0,134.0,34.6,33.2,33.7,33.3,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,68.0,96.0,78.0,21.0,8.0,20.0,16.0,148.0,105.0,148.0,124.0,88.0,48.0,88.0,58.0,37.0,36.7,36.7,36.7,1
2,2,262220,81.0,0.0,61.7,165.1,22.635548,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,185.0,88.0,140.0,134.0,34.0,25.9,34.0,34.0,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116.0,92.0,100.0,96.0,23.0,7.0,12.0,11.0,158.0,84.0,136.0,106.0,48.0,42.0,62.0,44.0,38.0,34.8,35.6,34.8,1
3,3,182697,67.0,1.0,100.0,190.5,27.555611,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,13.0,13.0,18.0,18.0,0.71,0.71,1.00,1.00,156.0,125.0,140.0,134.0,44.2,44.2,33.7,33.3,137.0,137.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.0,83.0,83.0,83.0,32.0,10.0,12.0,12.0,173.0,107.0,143.0,143.0,100.0,61.0,89.0,89.0,36.8,36.6,36.7,36.7,0
4,4,195124,59.0,0.0,156.6,165.1,57.451002,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,11.0,18.0,18.0,0.85,0.78,0.78,0.78,197.0,129.0,197.0,194.0,37.5,33.5,33.5,33.5,136.0,135.0,135.0,135.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.0,70.0,79.0,72.0,38.0,16.0,18.0,18.0,151.0,133.0,191.0,163.0,76.0,68.0,107.0,79.0,37.2,35.0,36.8,35.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96694,96694,147574,50.0,0.0,55.4,165.1,20.324301,False,True,False,False,False,False,False,False,2.8,2.8,2.8,0.2,0.2,8.0,7.0,7.0,7.0,0.86,0.73,0.73,0.73,182.0,121.0,182.0,167.0,26.0,26.0,26.0,26.0,143.0,140.0,143.0,143.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.0,48.0,72.0,65.0,28.0,14.0,17.0,14.0,155.0,91.0,113.0,111.0,72.0,52.0,62.0,55.0,37.8,34.9,36.7,36.7,1
96695,96695,164758,50.0,1.0,90.0,175.3,29.287256,False,False,False,True,False,False,False,False,3.0,2.9,3.1,0.7,0.6,18.0,17.0,18.0,18.0,1.00,0.93,1.00,1.00,150.0,108.0,140.0,134.0,34.6,33.2,33.7,33.3,139.0,138.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,89.0,101.0,89.0,40.0,12.0,40.0,22.0,161.0,134.0,161.0,134.0,102.0,82.0,102.0,82.0,36.6,36.2,36.6,36.6,1
96696,96696,197653,79.0,0.0,78.4,162.6,29.653433,False,False,False,True,False,False,False,False,3.5,3.5,3.1,0.7,0.7,32.0,32.0,18.0,18.0,1.07,1.07,1.00,1.00,139.0,139.0,140.0,134.0,39.0,39.0,33.7,33.3,140.0,140.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,78.0,96.0,94.0,37.0,20.0,28.0,25.0,164.0,109.0,147.0,139.0,97.0,63.0,83.0,81.0,37.4,36.4,37.4,37.4,1
96697,96697,219719,73.0,1.0,102.0,177.8,32.265371,False,True,False,False,False,False,False,False,3.3,3.3,3.3,0.5,0.5,31.0,30.0,18.0,18.0,2.65,2.41,1.00,1.00,346.0,55.0,140.0,134.0,33.0,31.0,33.0,33.0,142.0,139.0,139.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,58.0,101.0,92.0,34.0,12.0,24.0,24.0,156.0,123.0,134.0,134.0,82.0,60.0,70.0,70.0,35.1,32.5,34.2,33.7,0
96698,96698,157942,35.0,1.0,100.8,182.9,30.132358,False,True,False,False,False,False,False,False,3.0,2.9,3.1,0.7,0.6,13.0,13.0,13.0,13.0,1.06,1.06,1.06,1.06,100.0,100.0,100.0,100.0,34.6,33.2,33.7,33.3,135.0,135.0,135.0,135.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0,71.0,97.0,89.0,35.0,13.0,35.0,25.0,143.0,116.0,143.0,127.0,91.0,75.0,86.0,83.0,37.1,37.1,37.1,37.1,1

In [599]:
import os

FileNotFoundError: File /signature/data/train//underwritings.json does not exist

In [601]:
sgn = pd.read_json('C:\\Users\\asus\\Downloads\\signature\\data\\train\\underwritings.json')

In [602]:
sgn

,.underwritingdataclarity.clearfraud.clearfraudinquiry.thirtydaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.twentyfourhoursago,.underwritingdataclarity.clearfraud.clearfraudinquiry.oneminuteago,.underwritingdataclarity.clearfraud.clearfraudinquiry.onehourago,.underwritingdataclarity.clearfraud.clearfraudinquiry.ninetydaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.sevendaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.tenminutesago,.underwritingdataclarity.clearfraud.clearfraudinquiry.fifteendaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.threesixtyfivedaysago,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryonfilecurrentaddressconflict,.underwritingdataclarity.clearfraud.clearfraudindicator.totalnumberoffraudindicators,.underwritingdataclarity.clearfraud.clearfraudindicator.telephonenumberinconsistentwithaddress,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryageyoungerthanssnissuedate,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddresscautious,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddressnonresidential,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddresshighrisk,.underwritingdataclarity.clearfraud.clearfraudindicator.ssnreportedmorefrequentlyforanother,.underwritingdataclarity.clearfraud.clearfraudindicator.currentaddressreportedbytradeopenlt90days,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssninvalid,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssnissuedatecannotbeverified,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddresscautious,.underwritingdataclarity.clearfraud.clearfraudindicator.morethan3inquiriesinthelast30days,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddressnonresidential,.underwritingdataclarity.clearfraud.clearfraudindicator.creditestablishedpriortossnissuedate,.underwritingdataclarity.clearfraud.clearfraudindicator.driverlicenseformatinvalid,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssnrecordedasdeceased,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddresshighrisk,.underwritingdataclarity.clearfraud.clearfraudindicator.inquirycurrentaddressnotonfile,.underwritingdataclarity.clearfraud.clearfraudindicator.bestonfilessnissuedatecannotbeverified,.underwritingdataclarity.clearfraud.clearfraudindicator.highprobabilityssnbelongstoanother,.underwritingdataclarity.clearfraud.clearfraudindicator.maxnumberofssnswithanybankaccount,.underwritingdataclarity.clearfraud.clearfraudindicator.bestonfilessnrecordedasdeceased,.underwritingdataclarity.clearfraud.clearfraudindicator.currentaddressreportedbynewtradeonly,.underwritingdataclarity.clearfraud.clearfraudindicator.creditestablishedbeforeage18,.underwritingdataclarity.clearfraud.clearfraudindicator.telephonenumberinconsistentwithstate,.underwritingdataclarity.clearfraud.clearfraudindicator.driverlicenseinconsistentwithonfile,.underwritingdataclarity.clearfraud.clearfraudindicator.workphonepreviouslylistedascellphone,.underwritingdataclarity.clearfraud.clearfraudindicator.workphonepreviouslylistedashomephone,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamematch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressmatch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchtype,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamereasoncodedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchresult,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressreasoncodedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchtypedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.overallmatchresult,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonetype,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssndobreasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamereasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressreasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssndobmatch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.overallmatchreasoncode,clearfraudscore,underwritingid
0,8.0,2.0,2.0,2.0,8.0,2.0,2.0,5.0,10.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,partial,M,None,unavailable,(A8) Match to Last Name only,(M) Mobile Phone,partial,None,None,None,A8,match,6.0,871.0,54cbffcee4b0ba763e43144d
1,5.0,2.0,2.0,2.0,11.0,2.0,2.0,4.0,21.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,mismatch,M,None,unavailable,None,(M) Mobile Phone,partial,None,None,None,None,match,11.0,397.0,54cc0408e4b0418d9a7f78af
2,9.0,4.0,2.0,3.0,10.0,8.0,2.0,9.0,25.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,match,match,M,None,unavailable,None,(M) Mobile Phone,match,None,None,None,None,match,1.0,572.0,54cc0683e4b0418d9a80adb6
3,3.0,2.0,2.0,2.0,9.0,2.0,2.0,2.0,9.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,mismatch,M,None,unavailable,None,(M) Mobile Phone,partial,None,None,None,None,match,11.0,838.0,54cc0780e4b0ba763e43b74a
4,5.0,5.0,2.0,2.0,6.0,5.0,2.0,5.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,match,M,None,unavailable,None,(M) Mobile Phone,match,None,None,None,None,match,1.0,768.0,54cc1d67e4b0ba763e445b45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49747,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,24.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,mismatch,M,None,unavailable,None,(M) Mobile Phone,partial,None,None,None,None,match,11.0,677.0,58cc5706e4b0b0437e26b19c
49748,6.0,4.0,1.0,4.0,11.0,4.0,1.0,4.0,17.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,unavailable,M,None,unavailable,None,(M) Mobile Phone,partial,None,None,None,None,match,16.0,640.0,58cc5763e4b0b0437e272d38
49749,4.0,4.0,1.0,4.0,4.0,4.0,1.0,4.0,5.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,match,match,M,None,unavailable,None,(M) Mobile Phone,match,None,None,None,None,match,1.0,576.0,58cc57d4e4b0b0437e278bff
49750,3.0,3.0,2.0,2.0,3.0,3.0,2.0,3.0,25.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,match,M,None,unavailable,None,(M) Mobile Phone,match,None,None,None,None,match,1.0,830.0,58cc5916e4b0b0437e2b6e07
49751,5.0,3.0,2.0,2.0,6.0,3.0,2.0,4.0,12.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,partial,M,None,unavailable,(A8) Match to Last Name only,(M) Mobile Phone,partial,None,None,None,A8,match,6.0,793.0,58cc660ce4b0b0437e47de4a

In [603]:
sub = pd.read_csv('signature/data/submission/submission.csv')

In [604]:
test =pd.read_csv('signature/data/submission/test.csv')

In [605]:
sub

                           id  prediction
0    5829da64e4b051c58fcef11a         NaN
1    587b9b50e4b08f2486cd58c1         NaN
2    5789ce5de4b0022659314a39         NaN
3    58bf17bae4b0bec08aa033f9         NaN
4    58418a68e4b0bb9d6a0d716b         NaN
..                        ...         ...
995  552ed26ae4b04c4fa9920036         NaN
996  5706523ee4b06ef47cd41fc4         NaN
997  5825af9be4b051c58f1911f1         NaN
998  58b9dc7be4b0b6fcac965ad9         NaN
999  58546c54e4b08f245e96ba2e         NaN

[1000 rows x 2 columns]

In [606]:
test

,.underwritingdataclarity.clearfraud.clearfraudinquiry.thirtydaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.twentyfourhoursago,.underwritingdataclarity.clearfraud.clearfraudinquiry.oneminuteago,.underwritingdataclarity.clearfraud.clearfraudinquiry.onehourago,.underwritingdataclarity.clearfraud.clearfraudinquiry.ninetydaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.sevendaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.tenminutesago,.underwritingdataclarity.clearfraud.clearfraudinquiry.fifteendaysago,.underwritingdataclarity.clearfraud.clearfraudinquiry.threesixtyfivedaysago,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryonfilecurrentaddressconflict,.underwritingdataclarity.clearfraud.clearfraudindicator.totalnumberoffraudindicators,.underwritingdataclarity.clearfraud.clearfraudindicator.telephonenumberinconsistentwithaddress,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryageyoungerthanssnissuedate,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddresscautious,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddressnonresidential,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddresshighrisk,.underwritingdataclarity.clearfraud.clearfraudindicator.ssnreportedmorefrequentlyforanother,.underwritingdataclarity.clearfraud.clearfraudindicator.currentaddressreportedbytradeopenlt90days,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssninvalid,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssnissuedatecannotbeverified,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddresscautious,.underwritingdataclarity.clearfraud.clearfraudindicator.morethan3inquiriesinthelast30days,.underwritingdataclarity.clearfraud.clearfraudindicator.onfileaddressnonresidential,.underwritingdataclarity.clearfraud.clearfraudindicator.creditestablishedpriortossnissuedate,.underwritingdataclarity.clearfraud.clearfraudindicator.driverlicenseformatinvalid,.underwritingdataclarity.clearfraud.clearfraudindicator.inputssnrecordedasdeceased,.underwritingdataclarity.clearfraud.clearfraudindicator.inquiryaddresshighrisk,.underwritingdataclarity.clearfraud.clearfraudindicator.inquirycurrentaddressnotonfile,.underwritingdataclarity.clearfraud.clearfraudindicator.bestonfilessnissuedatecannotbeverified,.underwritingdataclarity.clearfraud.clearfraudindicator.highprobabilityssnbelongstoanother,.underwritingdataclarity.clearfraud.clearfraudindicator.maxnumberofssnswithanybankaccount,.underwritingdataclarity.clearfraud.clearfraudindicator.bestonfilessnrecordedasdeceased,.underwritingdataclarity.clearfraud.clearfraudindicator.currentaddressreportedbynewtradeonly,.underwritingdataclarity.clearfraud.clearfraudindicator.creditestablishedbeforeage18,.underwritingdataclarity.clearfraud.clearfraudindicator.telephonenumberinconsistentwithstate,.underwritingdataclarity.clearfraud.clearfraudindicator.driverlicenseinconsistentwithonfile,.underwritingdataclarity.clearfraud.clearfraudindicator.workphonepreviouslylistedascellphone,.underwritingdataclarity.clearfraud.clearfraudindicator.workphonepreviouslylistedashomephone,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamematch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressmatch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchtype,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamereasoncodedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchresult,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressreasoncodedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonematchtypedescription,.underwritingdataclarity.clearfraud.clearfraudidentityverification.overallmatchresult,.underwritingdataclarity.clearfraud.clearfraudidentityverification.phonetype,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssndobreasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssnnamereasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.nameaddressreasoncode,.underwritingdataclarity.clearfraud.clearfraudidentityverification.ssndobmatch,.underwritingdataclarity.clearfraud.clearfraudidentityverification.overallmatchreasoncode,underwritingid
0,6.0,3.0,3.0,3.0,8.0,5.0,3.0,5.0,18.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,match,match,M,NaN,unavailable,NaN,(M) Mobile Phone,match,NaN,NaN,NaN,NaN,match,1.0,54cce897e4b0ba763e46c138
1,5.0,2.0,2.0,2.0,14.0,2.0,2.0,2.0,29.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,mismatch,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,11.0,54dba4abe4b014f99557d7e3
2,4.0,2.0,2.0,2.0,32.0,2.0,2.0,2.0,43.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,match,M,NaN,unavailable,NaN,(M) Mobile Phone,match,NaN,NaN,NaN,NaN,match,1.0,54ea067fe4b0e9eaee82b86a
3,4.0,3.0,3.0,3.0,13.0,3.0,3.0,4.0,14.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,match,mismatch,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,11.0,54f78c15e4b058911ad4809a
4,5.0,4.0,4.0,4.0,6.0,4.0,4.0,4.0,15.0,1.0,6.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,match,unavailable,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,16.0,55109948e4b05ed2bca22bf8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8.0,7.0,1.0,7.0,17.0,7.0,7.0,7.0,18.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,mismatch,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,11.0,58c87ba6e4b0d10d6d755a42
996,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,13.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,match,M,NaN,unavailable,NaN,(M) Mobile Phone,match,NaN,NaN,NaN,NaN,match,1.0,58c96933e4b0d10d6e91641d
997,8.0,3.0,3.0,3.0,11.0,5.0,3.0,5.0,14.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,unavailable,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,16.0,58c9823fe4b0d10d6ee299b6
998,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,match,mismatch,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,match,11.0,58cac36de4b0b0437b1aaca2
999,26.0,26.0,1.0,26.0,26.0,26.0,23.0,26.0,26.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,mismatch,match,M,NaN,unavailable,NaN,(M) Mobile Phone,partial,NaN,NaN,NaN,NaN,mismatch,53.0,58cbdb6be4b0b0437ccac7ca

In [22]:
import pandas as pd
loan = pd.read_csv('/data/evaluation/loans.csv')
loan

FileNotFoundError: [Errno 2] No such file or directory: '/data/evaluation/loans.csv'

In [9]:
loans

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,B,475.00,2017-02-20T17:02:28.419000,True,2017-02-20T17:15:05.712000,0,True,1,1000,2554.26,MO,lead,40,Checked,58ab2121e4b0bf80497352a1,1
1,LL-I-04691446,668113dbf9ec99c1f7c83611dc35bd96,W,601.00,2015-11-16T20:44:10.919000,True,2015-11-17T15:14:41.516000,0,True,1,600,1826.00,NC,bvMandatory,6,Checked,564a4a64e4b033d9d5fce6a4,1
2,LL-I-04764159,8cf11204acfbbb4cd32e97b3b8b543ce,B,475.00,2015-11-18T19:32:31.613000,True,2015-11-18T19:47:28.382000,1,True,1,800,1883.93,OH,organic,0,Checked,5562061fe4b0d883ad962063,1
3,LL-I-05111303,f51e12172a176fa2f9b3bd70b7ac55be,W,601.00,2015-11-29T19:22:45.369000,True,2015-11-29T23:10:58.532000,0,True,1,600,1834.92,NC,lead,25,Checked,565b507fe4b0819f397e90d7,1
4,LL-I-04967757,e72b72f3186f4d2bd9be331de6512d57,B,449.99,2015-11-24T19:04:46.689000,True,2015-11-24T21:27:09.487000,0,True,1,800,1617.37,WI,lead,40,Checked,5654b4c3e4b0819f351f3567,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,bad53ab90ca7f1920788c123d3d1192c,B,360.00,2016-04-18T18:23:45.998000,True,2016-04-19T20:13:20.908000,1,True,1,1500,3365.66,IL,organic,0,Checked,571120b9e4b065aaa0b2c104,1
996,LL-I-04106790,7e92c8125ea802f895752061a6eabe4a,B,590.00,2015-10-28T01:20:57.344000,True,2015-10-29T16:13:10.965000,0,True,1,800,2405.80,OH,lead,75,Checked,55d86cafe4b015c919055c44,1
997,LL-I-08974550,740204e4bf738972f990026d6de6186a,B,449.99,2016-04-24T00:33:28,True,2016-04-25T18:07:58.711000,0,True,1,350,616.85,WI,bvMandatory,10,Checked,571c15a4e4b0cd5767cd6543,1
998,LL-I-17907485,85ea75317296db6450a8a2f412163f3a,W,590.00,2017-03-02T23:22:16.673000,True,2017-03-03T00:45:07.713000,0,True,1,1250,3972.97,OH,lead,25,Checked,58b8a924e4b0b6fcab29bca2,1
999,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,B,590.00,2016-12-20T22:02:40.654000,True,2016-12-20T22:13:26.742000,1,True,1,800,2364.94,PA,rc_returning,0,Checked,57cf287be4b09249a15fa807,1

In [47]:
loans= pd.get_dummies(loans,columns=['fpStatus'])

In [24]:
loans

,loanId,anon_ssn,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanAmount,...,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning
0,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,475.00,2017-02-20 17:02:28.419,True,2017-02-20 17:15:05.712,0,True,1,1000,...,False,False,False,False,False,True,False,False,False,False
1,LL-I-04691446,668113dbf9ec99c1f7c83611dc35bd96,601.00,2015-11-16 20:44:10.919,True,2015-11-17 15:14:41.516,0,True,1,600,...,False,False,True,True,False,False,False,False,False,False
2,LL-I-04764159,8cf11204acfbbb4cd32e97b3b8b543ce,475.00,2015-11-18 19:32:31.613,True,2015-11-18 19:47:28.382,1,True,1,800,...,False,False,False,False,False,False,False,True,False,False
3,LL-I-05111303,f51e12172a176fa2f9b3bd70b7ac55be,601.00,2015-11-29 19:22:45.369,True,2015-11-29 23:10:58.532,0,True,1,600,...,False,False,True,False,False,True,False,False,False,False
4,LL-I-04967757,e72b72f3186f4d2bd9be331de6512d57,449.99,2015-11-24 19:04:46.689,True,2015-11-24 21:27:09.487,0,True,1,800,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,bad53ab90ca7f1920788c123d3d1192c,360.00,2016-04-18 18:23:45.998,True,2016-04-19 20:13:20.908,1,True,1,1500,...,False,False,False,False,False,False,False,True,False,False
996,LL-I-04106790,7e92c8125ea802f895752061a6eabe4a,590.00,2015-10-28 01:20:57.344,True,2015-10-29 16:13:10.965,0,True,1,800,...,False,False,False,False,False,True,False,False,False,False
997,LL-I-08974550,740204e4bf738972f990026d6de6186a,449.99,NaT,True,2016-04-25 18:07:58.711,0,True,1,350,...,False,False,False,True,False,False,False,False,False,False
998,LL-I-17907485,85ea75317296db6450a8a2f412163f3a,590.00,2017-03-02 23:22:16.673,True,2017-03-03 00:45:07.713,0,True,1,1250,...,False,False,True,False,False,True,False,False,False,False
999,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,590.00,2016-12-20 22:02:40.654,True,2016-12-20 22:13:26.742,1,True,1,800,...,False,False,False,False,False,False,False,False,False,True

In [20]:
loans['originatedDate']=  pd.to_datetime(loans['originatedDate'],errors='coerce')

In [26]:
loans = loans.replace([True,False],[1,0])

C:\Users\asus\AppData\Local\Temp\ipykernel_67208\2711671719.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loans = loans.replace([True,False],[1,0])

In [27]:
loans

,loanId,anon_ssn,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanAmount,...,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning
0,LL-I-17438410,c9448f6494e012f94d8aef9a9bb10534,475.00,2017-02-20 17:02:28.419,1,2017-02-20 17:15:05.712,0,1,1,1000,...,0,0,0,0,0,1,0,0,0,0
1,LL-I-04691446,668113dbf9ec99c1f7c83611dc35bd96,601.00,2015-11-16 20:44:10.919,1,2015-11-17 15:14:41.516,0,1,1,600,...,0,0,1,1,0,0,0,0,0,0
2,LL-I-04764159,8cf11204acfbbb4cd32e97b3b8b543ce,475.00,2015-11-18 19:32:31.613,1,2015-11-18 19:47:28.382,1,1,1,800,...,0,0,0,0,0,0,0,1,0,0
3,LL-I-05111303,f51e12172a176fa2f9b3bd70b7ac55be,601.00,2015-11-29 19:22:45.369,1,2015-11-29 23:10:58.532,0,1,1,600,...,0,0,1,0,0,1,0,0,0,0
4,LL-I-04967757,e72b72f3186f4d2bd9be331de6512d57,449.99,2015-11-24 19:04:46.689,1,2015-11-24 21:27:09.487,0,1,1,800,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,bad53ab90ca7f1920788c123d3d1192c,360.00,2016-04-18 18:23:45.998,1,2016-04-19 20:13:20.908,1,1,1,1500,...,0,0,0,0,0,0,0,1,0,0
996,LL-I-04106790,7e92c8125ea802f895752061a6eabe4a,590.00,2015-10-28 01:20:57.344,1,2015-10-29 16:13:10.965,0,1,1,800,...,0,0,0,0,0,1,0,0,0,0
997,LL-I-08974550,740204e4bf738972f990026d6de6186a,449.99,NaT,1,2016-04-25 18:07:58.711,0,1,1,350,...,0,0,0,1,0,0,0,0,0,0
998,LL-I-17907485,85ea75317296db6450a8a2f412163f3a,590.00,2017-03-02 23:22:16.673,1,2017-03-03 00:45:07.713,0,1,1,1250,...,0,0,1,0,0,1,0,0,0,0
999,LL-I-13602063,0fa6b0212a0eb01ecf3ad16c6ef5bd2e,590.00,2016-12-20 22:02:40.654,1,2016-12-20 22:13:26.742,1,1,1,800,...,0,0,0,0,0,0,0,0,0,1

In [30]:
other = loans
loans.drop(columns=['anon_ssn','originated'] , inplace = True)

In [29]:
loans['originated'].value_counts()

originated
1    999
0      1
Name: count, dtype: int64

In [40]:
loans

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,fpStatus,clarityFraudId,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY
0,LL-I-17438410,475.00,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,Checked,58ab2121e4b0bf80497352a1,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,LL-I-04691446,601.00,2015-11-16 20:44:10.919,2015-11-17 15:14:41.516,0,1,1,600,1826.00,6,Checked,564a4a64e4b033d9d5fce6a4,1,0,0,0,0,1,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,LL-I-04764159,475.00,2015-11-18 19:32:31.613,2015-11-18 19:47:28.382,1,1,1,800,1883.93,0,Checked,5562061fe4b0d883ad962063,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,LL-I-05111303,601.00,2015-11-29 19:22:45.369,2015-11-29 23:10:58.532,0,1,1,600,1834.92,25,Checked,565b507fe4b0819f397e90d7,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,LL-I-04967757,449.99,2015-11-24 19:04:46.689,2015-11-24 21:27:09.487,0,1,1,800,1617.37,40,Checked,5654b4c3e4b0819f351f3567,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,360.00,2016-04-18 18:23:45.998,2016-04-19 20:13:20.908,1,1,1,1500,3365.66,0,Checked,571120b9e4b065aaa0b2c104,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,LL-I-04106790,590.00,2015-10-28 01:20:57.344,2015-10-29 16:13:10.965,0,1,1,800,2405.80,75,Checked,55d86cafe4b015c919055c44,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
997,LL-I-08974550,449.99,NaT,2016-04-25 18:07:58.711,0,1,1,350,616.85,10,Checked,571c15a4e4b0cd5767cd6543,1,1,0,0,0,0,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
998,LL-I-17907485,590.00,2017-03-02 23:22:16.673,2017-03-03 00:45:07.713,0,1,1,1250,3972.97,25,Checked,58b8a924e4b0b6fcab29bca2,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
999,LL-I-13602063,590.00,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,Checked,57cf287be4b09249a15fa807,1,1,0,0,0,0,0,0,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [38]:
pd.DataFrame(loans.isna().sum())

                                    0
loanId                              0
apr                                 0
applicationDate                     1
originatedDate                      3
nPaidOff                            0
approved                            0
isFunded                            0
loanAmount                          0
originallyScheduledPaymentAmount    0
leadCost                            0
fpStatus                           46
clarityFraudId                    158
hasCF                               0
payFrequency_B                      0
payFrequency_I                      0
payFrequency_M                      0
payFrequency_S                      0
payFrequency_W                      0
leadType_bvMandatory                0
leadType_california                 0
leadType_lead                       0
leadType_lionpay                    0
leadType_organic                    0
leadType_prescreen                  0
leadType_rc_returning               0
state_AL                            0
state_AZ                            0
state_CA                            0
state_CO                            0
state_CT                            0
state_DE                            0
state_FL                            0
state_GA                            0
state_HI                            0
state_IA                            0
state_ID                            0
state_IL                            0
state_IN                            0
state_KS                            0
state_KY                            0
state_LA                            0
state_MI                            0
state_MN                            0
state_MO                            0
state_MS                            0
state_NC                            0
state_ND                            0
state_NJ                            0
state_NM                            0
state_NV                            0
state_OH                            0
state_OK                            0
state_PA                            0
state_SC                            0
state_SD                            0
state_TN                            0
state_TX                            0
state_UT                            0
state_VA                            0
state_WA                            0
state_WI                            0
state_WY                            0

In [39]:
pd.set_option('display.max_rows',70)
pd.set_option('display.max_columns',70)

In [41]:
loans.dropna()

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,fpStatus,clarityFraudId,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY
0,LL-I-17438410,475.00,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,Checked,58ab2121e4b0bf80497352a1,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,LL-I-04691446,601.00,2015-11-16 20:44:10.919,2015-11-17 15:14:41.516,0,1,1,600,1826.00,6,Checked,564a4a64e4b033d9d5fce6a4,1,0,0,0,0,1,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,LL-I-04764159,475.00,2015-11-18 19:32:31.613,2015-11-18 19:47:28.382,1,1,1,800,1883.93,0,Checked,5562061fe4b0d883ad962063,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,LL-I-05111303,601.00,2015-11-29 19:22:45.369,2015-11-29 23:10:58.532,0,1,1,600,1834.92,25,Checked,565b507fe4b0819f397e90d7,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,LL-I-04967757,449.99,2015-11-24 19:04:46.689,2015-11-24 21:27:09.487,0,1,1,800,1617.37,40,Checked,5654b4c3e4b0819f351f3567,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,LL-I-09839147,625.00,2016-06-19 23:47:05.471,2016-06-24 20:15:22.638,0,1,1,350,1172.11,6,Checked,576d311de4b02bf642e2c03f,1,0,0,0,0,1,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
995,LL-I-08811902,360.00,2016-04-18 18:23:45.998,2016-04-19 20:13:20.908,1,1,1,1500,3365.66,0,Checked,571120b9e4b065aaa0b2c104,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,LL-I-04106790,590.00,2015-10-28 01:20:57.344,2015-10-29 16:13:10.965,0,1,1,800,2405.80,75,Checked,55d86cafe4b015c919055c44,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
998,LL-I-17907485,590.00,2017-03-02 23:22:16.673,2017-03-03 00:45:07.713,0,1,1,1250,3972.97,25,Checked,58b8a924e4b0b6fcab29bca2,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
999,LL-I-13602063,590.00,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,Checked,57cf287be4b09249a15fa807,1,1,0,0,0,0,0,0,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [44]:
loans.drop(columns=['clarityFraudId'],inplace= True)

In [45]:
loans

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,fpStatus,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY
0,LL-I-17438410,475.00,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,Checked,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,LL-I-04691446,601.00,2015-11-16 20:44:10.919,2015-11-17 15:14:41.516,0,1,1,600,1826.00,6,Checked,1,0,0,0,0,1,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,LL-I-04764159,475.00,2015-11-18 19:32:31.613,2015-11-18 19:47:28.382,1,1,1,800,1883.93,0,Checked,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,LL-I-05111303,601.00,2015-11-29 19:22:45.369,2015-11-29 23:10:58.532,0,1,1,600,1834.92,25,Checked,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,LL-I-04967757,449.99,2015-11-24 19:04:46.689,2015-11-24 21:27:09.487,0,1,1,800,1617.37,40,Checked,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,360.00,2016-04-18 18:23:45.998,2016-04-19 20:13:20.908,1,1,1,1500,3365.66,0,Checked,1,1,0,0,0,0,0,0,0,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,LL-I-04106790,590.00,2015-10-28 01:20:57.344,2015-10-29 16:13:10.965,0,1,1,800,2405.80,75,Checked,1,1,0,0,0,0,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
997,LL-I-08974550,449.99,NaT,2016-04-25 18:07:58.711,0,1,1,350,616.85,10,Checked,1,1,0,0,0,0,1,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
998,LL-I-17907485,590.00,2017-03-02 23:22:16.673,2017-03-03 00:45:07.713,0,1,1,1250,3972.97,25,Checked,1,0,0,0,0,1,0,0,1,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
999,LL-I-13602063,590.00,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,Checked,1,1,0,0,0,0,0,0,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [46]:
loans['fpStatus'].value_counts()

fpStatus
Checked      842
Rejected      94
Cancelled     11
Skipped        7
Name: count, dtype: int64

In [49]:
loans= loans.replace([True,False],[1,0] )

C:\Users\asus\AppData\Local\Temp\ipykernel_67208\4205500932.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  loans= loans.replace([True,False],[1,0] )

In [50]:
loans

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped
0,LL-I-17438410,475.00,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,LL-I-04691446,601.00,2015-11-16 20:44:10.919,2015-11-17 15:14:41.516,0,1,1,600,1826.00,6,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,LL-I-04764159,475.00,2015-11-18 19:32:31.613,2015-11-18 19:47:28.382,1,1,1,800,1883.93,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,LL-I-05111303,601.00,2015-11-29 19:22:45.369,2015-11-29 23:10:58.532,0,1,1,600,1834.92,25,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,LL-I-04967757,449.99,2015-11-24 19:04:46.689,2015-11-24 21:27:09.487,0,1,1,800,1617.37,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,360.00,2016-04-18 18:23:45.998,2016-04-19 20:13:20.908,1,1,1,1500,3365.66,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
996,LL-I-04106790,590.00,2015-10-28 01:20:57.344,2015-10-29 16:13:10.965,0,1,1,800,2405.80,75,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
997,LL-I-08974550,449.99,NaT,2016-04-25 18:07:58.711,0,1,1,350,616.85,10,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
998,LL-I-17907485,590.00,2017-03-02 23:22:16.673,2017-03-03 00:45:07.713,0,1,1,1250,3972.97,25,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
999,LL-I-13602063,590.00,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [51]:
payments

NameError: name 'payments' is not defined

In [52]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-00067673,1,False,2015-01-30T05:00:00,0.00,50.14,50.14,Checked,NaN
1,LL-I-00067673,2,False,2015-02-13T05:00:00,11.16,87.74,98.90,Checked,NaN
2,LL-I-00067673,3,False,2015-02-27T05:00:00,13.61,85.29,98.90,Checked,NaN
3,LL-I-00067673,4,False,2015-03-13T04:00:00,16.59,82.31,98.90,Checked,NaN
4,LL-I-00067673,5,False,2015-03-27T04:00:00,20.23,78.67,98.90,Checked,NaN
...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,False,2017-07-28T04:00:00,45.04,29.42,74.46,NaN,NaN
16641,LL-I-18589739,10,False,2017-08-11T04:00:00,49.81,24.65,74.46,NaN,NaN
16642,LL-I-18589739,11,False,2017-08-25T04:00:00,55.07,19.39,74.46,NaN,NaN
16643,LL-I-18589739,12,False,2017-09-08T04:00:00,60.89,13.57,74.46,NaN,NaN
16644,LL-I-18589739,13,False,2017-09-22T04:00:00,67.46,7.13,74.59,NaN,NaN

In [55]:
pay['paymentReturnCode']=pay['paymentReturnCode'].fillna('missing')

In [56]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-00067673,1,False,2015-01-30T05:00:00,0.00,50.14,50.14,Checked,missing
1,LL-I-00067673,2,False,2015-02-13T05:00:00,11.16,87.74,98.90,Checked,missing
2,LL-I-00067673,3,False,2015-02-27T05:00:00,13.61,85.29,98.90,Checked,missing
3,LL-I-00067673,4,False,2015-03-13T04:00:00,16.59,82.31,98.90,Checked,missing
4,LL-I-00067673,5,False,2015-03-27T04:00:00,20.23,78.67,98.90,Checked,missing
...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,False,2017-07-28T04:00:00,45.04,29.42,74.46,NaN,missing
16641,LL-I-18589739,10,False,2017-08-11T04:00:00,49.81,24.65,74.46,NaN,missing
16642,LL-I-18589739,11,False,2017-08-25T04:00:00,55.07,19.39,74.46,NaN,missing
16643,LL-I-18589739,12,False,2017-09-08T04:00:00,60.89,13.57,74.46,NaN,missing
16644,LL-I-18589739,13,False,2017-09-22T04:00:00,67.46,7.13,74.59,NaN,missing

In [66]:
pay= pd.get_dummies(pay,columns=['paymentStatus'])

In [59]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing
0,LL-I-00067673,1,False,2015-01-30T05:00:00,0.00,50.14,50.14,Checked,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,LL-I-00067673,2,False,2015-02-13T05:00:00,11.16,87.74,98.90,Checked,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,LL-I-00067673,3,False,2015-02-27T05:00:00,13.61,85.29,98.90,Checked,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,LL-I-00067673,4,False,2015-03-13T04:00:00,16.59,82.31,98.90,Checked,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,LL-I-00067673,5,False,2015-03-27T04:00:00,20.23,78.67,98.90,Checked,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,False,2017-07-28T04:00:00,45.04,29.42,74.46,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
16641,LL-I-18589739,10,False,2017-08-11T04:00:00,49.81,24.65,74.46,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
16642,LL-I-18589739,11,False,2017-08-25T04:00:00,55.07,19.39,74.46,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
16643,LL-I-18589739,12,False,2017-09-08T04:00:00,60.89,13.57,74.46,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
16644,LL-I-18589739,13,False,2017-09-22T04:00:00,67.46,7.13,74.59,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [62]:
pay['paymentStatus'].value_counts()

paymentStatus
Checked      7160
Cancelled    6483
Rejected      459
Pending       125
Skipped       114
Name: count, dtype: int64

In [64]:
pay2 = pd.read_csv('data/evaluation/payments.csv')

paymentStatus
Checked      7160
Cancelled    6483
Rejected      459
Pending       125
Skipped       114
Name: count, dtype: int64

In [67]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped
0,LL-I-00067673,1,False,2015-01-30T05:00:00,0.00,50.14,50.14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
1,LL-I-00067673,2,False,2015-02-13T05:00:00,11.16,87.74,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
2,LL-I-00067673,3,False,2015-02-27T05:00:00,13.61,85.29,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
3,LL-I-00067673,4,False,2015-03-13T04:00:00,16.59,82.31,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
4,LL-I-00067673,5,False,2015-03-27T04:00:00,20.23,78.67,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,False,2017-07-28T04:00:00,45.04,29.42,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16641,LL-I-18589739,10,False,2017-08-11T04:00:00,49.81,24.65,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16642,LL-I-18589739,11,False,2017-08-25T04:00:00,55.07,19.39,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16643,LL-I-18589739,12,False,2017-09-08T04:00:00,60.89,13.57,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16644,LL-I-18589739,13,False,2017-09-22T04:00:00,67.46,7.13,74.59,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [69]:
pay['paymentDate']=  pd.to_datetime(pay['paymentDate'],errors='coerce')

In [73]:
filt = pay['paymentDate'].isna()
pay= pay[~filt]

In [74]:
pay

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped
0,LL-I-00067673,1,False,2015-01-30 05:00:00,0.00,50.14,50.14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
1,LL-I-00067673,2,False,2015-02-13 05:00:00,11.16,87.74,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
2,LL-I-00067673,3,False,2015-02-27 05:00:00,13.61,85.29,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
3,LL-I-00067673,4,False,2015-03-13 04:00:00,16.59,82.31,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
4,LL-I-00067673,5,False,2015-03-27 04:00:00,20.23,78.67,98.90,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,False,2017-07-28 04:00:00,45.04,29.42,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16641,LL-I-18589739,10,False,2017-08-11 04:00:00,49.81,24.65,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16642,LL-I-18589739,11,False,2017-08-25 04:00:00,55.07,19.39,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16643,LL-I-18589739,12,False,2017-09-08 04:00:00,60.89,13.57,74.46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16644,LL-I-18589739,13,False,2017-09-22 04:00:00,67.46,7.13,74.59,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [75]:
pay.replace([True,False],[1,0])

C:\Users\asus\AppData\Local\Temp\ipykernel_67208\1228226203.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pay.replace([True,False],[1,0])

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped
0,LL-I-00067673,1,0,2015-01-30 05:00:00,0.00,50.14,50.14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
1,LL-I-00067673,2,0,2015-02-13 05:00:00,11.16,87.74,98.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
2,LL-I-00067673,3,0,2015-02-27 05:00:00,13.61,85.29,98.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
3,LL-I-00067673,4,0,2015-03-13 04:00:00,16.59,82.31,98.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
4,LL-I-00067673,5,0,2015-03-27 04:00:00,20.23,78.67,98.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,LL-I-18589739,9,0,2017-07-28 04:00:00,45.04,29.42,74.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16641,LL-I-18589739,10,0,2017-08-11 04:00:00,49.81,24.65,74.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16642,LL-I-18589739,11,0,2017-08-25 04:00:00,55.07,19.39,74.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16643,LL-I-18589739,12,0,2017-09-08 04:00:00,60.89,13.57,74.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16644,LL-I-18589739,13,0,2017-09-22 04:00:00,67.46,7.13,74.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [76]:
pay = pay.replace([True,False],[1,0])

C:\Users\asus\AppData\Local\Temp\ipykernel_67208\1842318319.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pay = pay.replace([True,False],[1,0])

In [115]:
loans.columns

Index(['loanId', 'apr', 'applicationDate', 'originatedDate', 'nPaidOff',
       'approved', 'isFunded', 'loanAmount',
       'originallyScheduledPaymentAmount', 'leadCost', 'hasCF',
       'payFrequency_B', 'payFrequency_I', 'payFrequency_M', 'payFrequency_S',
       'payFrequency_W', 'leadType_bvMandatory', 'leadType_california',
       'leadType_lead', 'leadType_lionpay', 'leadType_organic',
       'leadType_prescreen', 'leadType_rc_returning', 'state_AL', 'state_AZ',
       'state_CA', 'state_CO', 'state_CT', 'state_DE', 'state_FL', 'state_GA',
       'state_HI', 'state_IA', 'state_ID', 'state_IL', 'state_IN', 'state_KS',
       'state_KY', 'state_LA', 'state_MI', 'state_MN', 'state_MO', 'state_MS',
       'state_NC', 'state_ND', 'state_NJ', 'state_NM', 'state_NV', 'state_OH',
       'state_OK', 'state_PA', 'state_SC', 'state_SD', 'state_TN', 'state_TX',
       'state_UT', 'state_VA', 'state_WA', 'state_WI', 'state_WY',
       'fpStatus_Cancelled', 'fpStatus_Checked', 'fpStatus_Rejected',
       'fpStatus_Skipped'],
      dtype='object')

In [78]:
pay.dtypes

loanId                               object
installmentIndex                      int64
isCollection                          int64
paymentDate                  datetime64[ns]
principal                           float64
fees                                float64
paymentAmount                       float64
paymentReturnCode_C01                 int64
paymentReturnCode_C03                 int64
paymentReturnCode_C05                 int64
paymentReturnCode_MISSED              int64
paymentReturnCode_R01                 int64
paymentReturnCode_R02                 int64
paymentReturnCode_R03                 int64
paymentReturnCode_R04                 int64
paymentReturnCode_R07                 int64
paymentReturnCode_R08                 int64
paymentReturnCode_R09                 int64
paymentReturnCode_R10                 int64
paymentReturnCode_R16                 int64
paymentReturnCode_RUP                 int64
paymentReturnCode_RXS                 int64
paymentReturnCode_missing             int64
paymentStatus_Cancelled               int64
paymentStatus_Checked                 int64
paymentStatus_Pending                 int64
paymentStatus_Rejected                int64
paymentStatus_Skipped                 int64
dtype: object

In [79]:
loans

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MI,state_MN,state_MO,state_MS,state_NC,state_ND,state_NJ,state_NM,state_NV,state_OH,state_OK,state_PA,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped
0,LL-I-17438410,475.00,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,LL-I-04691446,601.00,2015-11-16 20:44:10.919,2015-11-17 15:14:41.516,0,1,1,600,1826.00,6,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,LL-I-04764159,475.00,2015-11-18 19:32:31.613,2015-11-18 19:47:28.382,1,1,1,800,1883.93,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,LL-I-05111303,601.00,2015-11-29 19:22:45.369,2015-11-29 23:10:58.532,0,1,1,600,1834.92,25,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,LL-I-04967757,449.99,2015-11-24 19:04:46.689,2015-11-24 21:27:09.487,0,1,1,800,1617.37,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,LL-I-08811902,360.00,2016-04-18 18:23:45.998,2016-04-19 20:13:20.908,1,1,1,1500,3365.66,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
996,LL-I-04106790,590.00,2015-10-28 01:20:57.344,2015-10-29 16:13:10.965,0,1,1,800,2405.80,75,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
997,LL-I-08974550,449.99,NaT,2016-04-25 18:07:58.711,0,1,1,350,616.85,10,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
998,LL-I-17907485,590.00,2017-03-02 23:22:16.673,2017-03-03 00:45:07.713,0,1,1,1250,3972.97,25,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
999,LL-I-13602063,590.00,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [80]:
loans.dtypes

loanId                                      object
apr                                        float64
applicationDate                     datetime64[ns]
originatedDate                      datetime64[ns]
nPaidOff                                     int64
approved                                     int64
isFunded                                     int64
loanAmount                                   int64
originallyScheduledPaymentAmount           float64
leadCost                                     int64
hasCF                                        int64
payFrequency_B                               int64
payFrequency_I                               int64
payFrequency_M                               int64
payFrequency_S                               int64
payFrequency_W                               int64
leadType_bvMandatory                         int64
leadType_california                          int64
leadType_lead                                int64
leadType_lionpay                             int64
leadType_organic                             int64
leadType_prescreen                           int64
leadType_rc_returning                        int64
state_AL                                     int64
state_AZ                                     int64
state_CA                                     int64
state_CO                                     int64
state_CT                                     int64
state_DE                                     int64
state_FL                                     int64
state_GA                                     int64
state_HI                                     int64
state_IA                                     int64
state_ID                                     int64
state_IL                                     int64
state_IN                                     int64
state_KS                                     int64
state_KY                                     int64
state_LA                                     int64
state_MI                                     int64
state_MN                                     int64
state_MO                                     int64
state_MS                                     int64
state_NC                                     int64
state_ND                                     int64
state_NJ                                     int64
state_NM                                     int64
state_NV                                     int64
state_OH                                     int64
state_OK                                     int64
state_PA                                     int64
state_SC                                     int64
state_SD                                     int64
state_TN                                     int64
state_TX                                     int64
state_UT                                     int64
state_VA                                     int64
state_WA                                     int64
state_WI                                     int64
state_WY                                     int64
fpStatus_Cancelled                           int64
fpStatus_Checked                             int64
fpStatus_Rejected                            int64
fpStatus_Skipped                             int64
dtype: object

In [102]:
merged_df = pd.merge(loans, pay, on='loanId', how='inner')

In [82]:
merged_df

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,...,state_VA,state_WA,state_WI,state_WY,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped
0,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0,2017-03-03 05:00:00,66.33,130.14,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
1,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,2,0,2017-03-17 04:00:00,26.36,170.11,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
2,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,3,0,2017-03-31 04:00:00,31.17,165.30,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,4,0,2017-04-14 04:00:00,36.84,159.63,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,5,0,2017-04-28 04:00:00,43.56,152.91,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16078,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,9,0,2017-04-21 04:00:00,65.63,116.31,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16079,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,10,0,2017-05-05 04:00:00,80.48,101.46,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16080,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,11,0,2017-05-19 04:00:00,98.69,83.25,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16081,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,12,0,2017-06-02 04:00:00,121.03,60.91,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16082,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,13,0,2017-06-16 04:00:00,148.14,33.52,181.66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [116]:
fn = pd.read_csv('final_data.csv')

In [117]:
fn

,Unnamed: 0.1,Unnamed: 0,apr,applicationDate,originatedDate,nPaidOff,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_express,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,leadType_repeat,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,state_AK,state_AL,state_AZ,state_CA,state_CO,...,paymentAmount,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Complete,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Rejected Awaiting Retry,paymentStatus_Skipped,paymentReturnCode_C01,paymentReturnCode_C02,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_LPP01,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R06,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R13,paymentReturnCode_R15,paymentReturnCode_R16,paymentReturnCode_R20,paymentReturnCode_R29,paymentReturnCode_R99,paymentReturnCode_RAF,paymentReturnCode_RBW,paymentReturnCode_RUP,paymentReturnCode_RWC,paymentReturnCode_RXL,paymentReturnCode_RXS
0,0,0,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,...,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,...,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,2,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,...,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,3,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,...,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,4,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,...,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253788,264984,264984,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253789,264985,264985,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253790,264986,264986,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253791,264987,264987,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253792,264988,264988,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...,39.85,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [85]:
merged_df

,loanId,apr,applicationDate,originatedDate,nPaidOff,approved,isFunded,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,...,state_VA,state_WA,state_WI,state_WY,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS,paymentReturnCode_missing,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped
0,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0,2017-03-03 05:00:00,66.33,130.14,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
1,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,2,0,2017-03-17 04:00:00,26.36,170.11,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
2,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,3,0,2017-03-31 04:00:00,31.17,165.30,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,4,0,2017-04-14 04:00:00,36.84,159.63,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,LL-I-17438410,475.0,2017-02-20 17:02:28.419,2017-02-20 17:15:05.712,0,1,1,1000,2554.26,40,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,5,0,2017-04-28 04:00:00,43.56,152.91,196.47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16078,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,9,0,2017-04-21 04:00:00,65.63,116.31,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16079,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,10,0,2017-05-05 04:00:00,80.48,101.46,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16080,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,11,0,2017-05-19 04:00:00,98.69,83.25,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16081,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,12,0,2017-06-02 04:00:00,121.03,60.91,181.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16082,LL-I-13602063,590.0,2016-12-20 22:02:40.654,2016-12-20 22:13:26.742,1,1,1,800,2364.94,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,13,0,2017-06-16 04:00:00,148.14,33.52,181.66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [138]:
columns_only_in_first = set(merged_df.columns) - set(fn.columns)

# Print the result
print("Columns in the first file but not in the second file:")
for column in columns_only_in_first:
    print(column+",")

Columns in the first file but not in the second file:

In [135]:
columns_to_print = [
'approved',
'paymentReturnCode_missing',
'loanId',
    
]
merged_df.drop(columns=columns_to_print,inplace= True)

In [142]:
fn.to_csv('nik_train.csv')
merged_df.to_csv('nik_merged.csv')

In [141]:
fn

,apr,applicationDate,originatedDate,nPaidOff,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,leadCost,hasCF,payFrequency_B,payFrequency_I,payFrequency_M,payFrequency_S,payFrequency_W,leadType_bvMandatory,leadType_california,leadType_lead,leadType_lionpay,leadType_organic,leadType_prescreen,leadType_rc_returning,fpStatus_Cancelled,fpStatus_Checked,fpStatus_Rejected,fpStatus_Skipped,state_AL,state_AZ,state_CA,state_CO,state_CT,state_DE,state_FL,state_GA,state_HI,...,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_WA,state_WI,state_WY,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus_Cancelled,paymentStatus_Checked,paymentStatus_Pending,paymentStatus_Rejected,paymentStatus_Skipped,paymentReturnCode_C01,paymentReturnCode_C03,paymentReturnCode_C05,paymentReturnCode_MISSED,paymentReturnCode_R01,paymentReturnCode_R02,paymentReturnCode_R03,paymentReturnCode_R04,paymentReturnCode_R07,paymentReturnCode_R08,paymentReturnCode_R09,paymentReturnCode_R10,paymentReturnCode_R16,paymentReturnCode_RUP,paymentReturnCode_RXS
0,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1,0,2016-01-27 05:00:00,151.98,114.49,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2,0,2016-02-10 05:00:00,49.08,217.39,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3,0,2016-02-24 05:00:00,52.83,213.64,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4,0,2016-03-09 05:00:00,56.86,209.61,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,199.0,2016-01-19 22:07:36.778,2016-01-20 15:49:18.846,0.0,1,0,3000.0,6395.19,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5,0,2016-03-23 04:00:00,61.20,205.27,266.47,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253788,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,23,0,2017-05-25 04:00:00,21.85,17.38,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253789,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,24,0,2017-06-01 04:00:00,24.56,14.67,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253790,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25,0,2017-06-08 04:00:00,27.59,11.64,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253791,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,26,0,2017-06-15 04:00:00,31.01,8.22,39.23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
253792,645.0,2016-12-16 20:20:30.157,2016-12-16 23:15:06.874,0.0,1,0,300.0,1034.38,6,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,27,0,2017-06-22 04:00:00,35.46,4.39,39.85,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [109]:
fn.replace([True,False],[1,0] inplace=True)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (493601480.py, line 1)

In [121]:
fn.replace([True,False],[1,0] ,inplace=True)

In [125]:
fn.to_csv('Last2.csv')

In [127]:
fn.shape

(253793, 111)

In [ ]:
data = [
[['mohamed','']],
[[]],
[[]],
]